// SPDX-License-Identifier: AGPL-3.0-or-later
import {describe,it,expect} from 'vitest';
import {inventoryCanonical,rowObjectReferences} from './service-inventory.js';
const tenant='4d0bd5cc-76c5-4df4-b763-63d0f2484777',id='89dbf776-904b-4a49-96ab-e946f49ea2f9',key=tenant+'/objects/model.glb',sha='a'.repeat(64);
const row={tenant_id:tenant,id,object_key:key,target_key:tenant+'/objects/final.glb',bytes:123,sha256:sha};
describe('service inventory typed references',()=>{
 it('includes retained/deleted assets and marks unwritten outbox destination optional',()=>{const r=rowObjectReferences('assets',{...row,state:'quarantine',deleted_at:'2020-01-01'});expect(r.references.map(v=>[v.key,v.required])).toEqual([[key,true],[row.target_key,false]]);expect(r.references[0].expectedSha256).toBe(sha);});
 it('uses derivative expectations and refuses foreign tenant keys',()=>{expect(rowObjectReferences('asset_derivatives',{...row,metadata:{objectKey:key,bytes:42,sha256:sha}}).references[0].expectedBytes).toBe(42);expect(rowObjectReferences('assets',{...row,object_key:'another/objects/x',state:'approved'}).issues[0].code).toBe('INVALID_REFERENCE');});
 it('retains optional pending and required committed imports/audio',()=>{const source={...row,approved_key:row.target_key,expected_bytes:123,expected_hash:sha};expect(rowObjectReferences('import_jobs',{...source,state:'uploading'}).references.every(v=>!v.required)).toBe(true);expect(rowObjectReferences('import_jobs',{...source,state:'approved'}).references.every(v=>v.required)).toBe(true);expect(rowObjectReferences('studio_audio',{...row,state:'approved',revoked:true}).references[0].required).toBe(true);});
 it('records chunk aggregate hashes only for fully received OEX archive',()=>{const source={...row,staging_keys:[key,row.target_key],cleanup_keys:[tenant+'/oex/job/model.glb'],expected_bytes:123,payload_sha256:sha};const r=rowObjectReferences('oex_import_jobs',{...source,state:'queued'});expect(r.references[1].aggregate).toMatchObject({index:1,count:2,bytes:123,sha256:sha});expect(r.references[2].required).toBe(false);expect(rowObjectReferences('oex_import_jobs',{...source,state:'complete'}).references.every(v=>!v.required)).toBe(true);});
 it('rejects unsafe keys and malformed hashes, without treating arbitrary metadata strings as references',()=>{expect(rowObjectReferences('publication_assets',{...row,object_key:tenant+'/../outside'}).issues[0].code).toBe('INVALID_REFERENCE');expect(rowObjectReferences('assets',{...row,sha256:'invalid'}).issues[0].code).toBe('INVALID_EXPECTED_HASH');expect(rowObjectReferences('artworks',{...row,metadata:{url:key}}).references).toEqual([]);});
 it('freezes include revoked historical runtime and ordered full OEX archive',()=>{const manifest={oex:{bytes:123,sha256:sha},runtime:{files:[{path:'index.html',bytes:1,sha256:sha}]}},inventory={oex:[key],runtime:[{path:'index.html',key:row.target_key}]};const r=rowObjectReferences('exhibition_freezes',{...row,manifest,inventory});expect(r.references).toHaveLength(2);expect(r.references[0].aggregate?.sha256).toBe(sha);expect(r.references[1].expectedBytes).toBe(1);expect(rowObjectReferences('freeze_requests',{...row,object_keys:[key],state:'creating'}).references[0].required).toBe(false);expect(rowObjectReferences('freeze_requests',{...row,object_keys:[key],state:'complete'}).references[0].required).toBe(true);});
 it('refuses duplicate runtime mappings and invalid aggregate inventory',()=>{const manifest={oex:{bytes:123,sha256:sha},runtime:{files:[{path:'index.html',bytes:1,sha256:sha}]}},inventory={oex:[],runtime:[{path:'index.html',key},{path:'index.html',key}]};const r=rowObjectReferences('exhibition_freezes',{...row,manifest,inventory});expect(r.issues.map(v=>v.code)).toContain('INVALID_AGGREGATE');expect(r.issues.map(v=>v.code)).toContain('INVALID_INVENTORY');});
 it('canonical hashes preserve every value but ignore property insertion order',()=>{expect(inventoryCanonical({z:[2,1],a:{b:'secret'}})).toBe(inventoryCanonical({a:{b:'secret'},z:[2,1]}));expect(inventoryCanonical({a:1})).not.toBe(inventoryCanonical({a:2}));});
});
