// SPDX-License-Identifier: AGPL-3.0-or-later
import { test } from "vitest";
import assert from "node:assert/strict";
import { distanceGain, footstepWave, StrideClock, verifyPcmWav } from "./audio.ts";
import type { NavigationState } from "./navigation.ts";
const state=(x:number, extra:Partial<NavigationState>={}):NavigationState=>({eyePosition:[x,1.65,0],yaw:0,velocity:[1.3,0,0],grounded:true,steps:1,paused:false,blocked:false,recovered:false,...extra});
test("distance attenuation is bounded, silence outside radius and invalid distances",()=>{assert.equal(distanceGain(0,3),1);assert.equal(distanceGain(1.5,3),0.25);assert.equal(distanceGain(3,3),0);assert.equal(distanceGain(4,3),0);assert.equal(distanceGain(NaN,3),0);assert.equal(distanceGain(1,0),0);});
test("original four floor waveforms have bounded finite distinct energy and deterministic output",()=>{const waves=["wood","stone","concrete","carpet"].map(m=>footstepWave(m as "wood",48000));for(const wave of waves){assert.ok(wave.length<10000);assert.ok(wave.every(n=>Number.isFinite(n)&&Math.abs(n)<1));}assert.notDeepEqual(waves[0],waves[1]);assert.deepEqual(waves[0],footstepWave("wood",48000));const energy=(wave:Float32Array)=>wave.reduce((n,v)=>n+v*v,0);assert.ok(energy(waves[3]!)<energy(waves[0]!));});
test("footsteps require actual grounded displacement; stationary collision and keyboard look cannot step",()=>{const clock=new StrideClock();assert.equal(clock.advance(state(0),true),false);for(let i=0;i<100;i++)assert.equal(clock.advance(state(0,{yaw:i,blocked:true}),true),false);for(let i=1;i<5;i++)assert.equal(clock.advance(state(i*.1),true),false);assert.equal(clock.advance(state(.6),true),true);assert.equal(clock.advance(state(.7,{grounded:false}),true),false);assert.equal(clock.advance(state(.8,{paused:true}),true),false);assert.equal(clock.advance(state(.9),false),false);});
test("footstep teleports and recovery reset stride; pause prevents deferred step",()=>{const clock=new StrideClock();clock.advance(state(0),true);assert.equal(clock.advance(state(10),true),false);assert.equal(clock.advance(state(10.1,{recovered:true}),true),false);clock.advance(state(10.3),true);clock.reset();assert.equal(clock.advance(state(11),true),false);});
function wav(seconds=1){const data=16000*seconds, buffer=new ArrayBuffer(44+data),view=new DataView(buffer);for(const [at,tag] of [[0,"RIFF"],[8,"WAVE"],[12,"fmt "],[36,"data"]] as const)for(let i=0;i<4;i++)view.setUint8(at+i,tag.charCodeAt(i));view.setUint32(4,buffer.byteLength-8,true);view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,8000,true);view.setUint32(28,16000,true);view.setUint16(32,2,true);view.setUint16(34,16,true);view.setUint32(40,data,true);return buffer;}
test("WAV predecode validates actual PCM16 duration and channels",()=>{assert.deepEqual(verifyPcmWav(wav()),{channels:1,sampleRate:8000,duration:1});assert.throws(()=>verifyPcmWav(wav(61)),/AUDIO_WAV_INVALID/);const bad=wav();new DataView(bad).setUint16(34,8,true);assert.throws(()=>verifyPcmWav(bad),/AUDIO_WAV_INVALID/);assert.throws(()=>verifyPcmWav(new ArrayBuffer(10)),/AUDIO_WAV_INVALID/);});
test("WAV rejects truncated payload, false RIFF length and misleading block alignment",()=>{const bad=wav();new DataView(bad).setUint32(40,99999999,true);assert.throws(()=>verifyPcmWav(bad));const length=wav();new DataView(length).setUint32(4,123,true);assert.throws(()=>verifyPcmWav(length));const align=wav();new DataView(align).setUint16(32,4,true);assert.throws(()=>verifyPcmWav(align));});
