// SPDX-License-Identifier: AGPL-3.0-or-later
import {test,expect} from "vitest";
import type {Exhibition} from "@exhibitos/spec";
import {occlusionGain,authoredDistanceGain} from "./audio-geometry";
function doc(){return {rooms:[{id:"room",transform:{position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]}}],surfaces:[{id:"wall",roomId:"room",type:"wall",transform:{position:[0,0,0],rotation:[0,0,0,1],scale:[1,1,1]},dimensions:{width:10,height:10}}],openings:[]} as unknown as Exhibition;}
test("straight wall blocks, valid openings transmit and outside-bound rays bypass",()=>{const d=doc();expect(occlusionGain(d,[0,0,-2],[0,0,2],.2)).toBe(.2);expect(occlusionGain(d,[6,0,-2],[6,0,2],.2)).toBe(1);d.openings=[{id:"door",surfaceId:"wall",offset:[0,0],dimensions:{width:2,height:3},type:"door",exterior:false}];expect(occlusionGain(d,[0,0,-2],[0,0,2],.2)).toBe(1);expect(occlusionGain(d,[2,0,-2],[2,0,2],.2)).toBe(.2);});
test("rotated translated room and generated plane transforms use same geometry",()=>{const d=doc();d.rooms[0]!.transform.position=[5,0,0];d.rooms[0]!.transform.rotation=[0,Math.SQRT1_2,0,Math.SQRT1_2];expect(occlusionGain(d,[3,0,0],[7,0,0],.3)).toBe(.3);expect(occlusionGain(d,[3,0,9],[7,0,9],.3)).toBe(1);});
test("coincident room boundary counted once, separate walls multiply bounded attenuation",()=>{const d=doc();d.surfaces.push({...d.surfaces[0]!,id:"duplicate"});expect(occlusionGain(d,[0,0,-2],[0,0,2],.2)).toBe(.2);d.surfaces.push({...d.surfaces[0]!,id:"another",transform:{...d.surfaces[0]!.transform,position:[0,0,1]}});expect(occlusionGain(d,[0,0,-2],[0,0,2],.2)).toBeCloseTo(.04);expect(occlusionGain(d,[NaN,0,-2],[0,0,2],.2)).toBe(0);});
test("authored inverse attenuation respects reference max and rolloff and rejects nonfinite",()=>{expect(authoredDistanceGain(0,1,20,1)).toBe(1);expect(authoredDistanceGain(2,1,20,1)).toBe(.5);expect(authoredDistanceGain(10,1,20,0)).toBe(1);expect(authoredDistanceGain(20,1,20,0)).toBe(0);for(const value of [NaN,Infinity,-1])expect(authoredDistanceGain(value,1,20,1)).toBe(0);});
