import { describe, it, expect } from "vitest";
import { createServer } from "node:http";
import { createHash } from "node:crypto";
import { AssetScheduler, MemoryAssetCache, DEVICE_BUDGETS, selectAssetVariant, fetchVerifiedAsset } from "./loading";
import { syntheticArtwork } from "../placement/model";
import { LOD_NAMESPACE, validateViewerLod } from "@exhibitos/studio-contract";
const tick=()=>new Promise(r=>setTimeout(r,0));
describe("bounded Viewer loading",()=>{
 it("prioritizes queued demand, deduplicates and retains cancellation slots until settlement then retries",async()=>{const started:string[]=[],finish=new Map<string,(v:string)=>void>(),discarded:string[]=[];const s=new AssetScheduler<string>({concurrency:1,load:key=>{started.push(key);return new Promise(r=>finish.set(key,r));},onDiscard:v=>discarded.push(v)});const far=s.request("far",20),near=s.request("near",1);expect(s.request("near",3)).toBe(near);await tick();expect(started).toEqual(["near"]);const aborted=expect(near).rejects.toMatchObject({name:"AbortError"});s.cancel("near");await aborted;await tick();expect(s.stats().active).toBe(1);expect(started).toEqual(["near"]);finish.get("near")!("late");await tick();expect(discarded).toEqual(["late"]);expect(started).toEqual(["near","far"]);finish.get("far")!("ok");expect(await far).toBe("ok");const again=s.retry("near");await tick();finish.get("near")!("retry");expect(await again).toBe("retry");s.dispose();expect(s.stats()).toMatchObject({active:0,queued:0,completed:2,cancelled:1});});
 it("evicts only unpinned LRU resources and disposes rejected allocations and teardown",()=>{const disposed:string[]=[];const c=new MemoryAssetCache<string>(10,v=>disposed.push(v));c.set("a","a",6);c.acquire("a");expect(c.set("b","b",6)).toBe(false);expect(disposed).toEqual(["b"]);expect(c.delete("a")).toBe(false);c.release("a");expect(c.set("c","c",6)).toBe(true);expect(disposed).toEqual(["b","a"]);expect(c.stats().bytes).toBe(6);c.clear();expect(disposed).toEqual(["b","a","c"]);});
 it("selects actual qualified coarse detail and refuses known over-budget fallback including case-varied byte aliases",()=>{const a=syntheticArtwork("sculpture"),full=a.assets[0]!;full.bytes=1000;const low={...full,id:"a0000000-0000-4000-8000-000000000001",bytes:100};a.assets.push(low);a.extensions={[LOD_NAMESPACE]:{version:1,variants:[{assetId:full.id,detail:"full",triangles:30000},{assetId:low.id.toUpperCase(),detail:"coarse",triangles:3000}]}};expect(validateViewerLod(a).valid).toBe(true);expect(selectAssetVariant(a,10,DEVICE_BUDGETS.compact).id).toBe(low.id);low.bytes=2000;expect(validateViewerLod(a).valid).toBe(false);a.assets.pop();a.extensions={[LOD_NAMESPACE]:{version:1,variants:[{assetId:full.id,detail:"full",triangles:30000}]}};expect(()=>selectAssetVariant(a,1,DEVICE_BUDGETS.compact)).toThrow("ASSET_BUDGET_EXCEEDED");});
 it("verifies streamed response identity and hash, stops overflow before allocating declared body, rejects wrong revision",async()=>{const a=syntheticArtwork("image"),inventory=a.assets[0]!,payload=new Uint8Array([1,2,3]);inventory.bytes=3;inventory.sha256=createHash("sha256").update(payload).digest("hex");const publicationId="a0000000-0000-4000-8000-000000000001",revisionSha256="1".repeat(64),asset={assetId:inventory.id,mime:inventory.mime,url:`/api/v1/publications/${publicationId}/assets/${inventory.id}`},signal=new AbortController().signal,headers={"content-type":inventory.mime,"x-exhibitos-publication-revision":revisionSha256};const fetcher=(async()=>new Response(payload,{headers})) as typeof fetch;expect(new Uint8Array(await fetchVerifiedAsset({publicationId,revisionSha256,asset,inventory,signal,fetcher}))).toEqual(payload);let cancelled=false;const oversized=(async()=>new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(4));},cancel(){cancelled=true;}}),{headers})) as typeof fetch;await expect(fetchVerifiedAsset({publicationId,revisionSha256,asset,inventory,signal,fetcher:oversized})).rejects.toThrow("ASSET_INTEGRITY");expect(cancelled).toBe(true);await expect(fetchVerifiedAsset({publicationId,revisionSha256,asset,inventory,signal,fetcher:(async()=>new Response(payload,{headers:{...headers,"x-exhibitos-publication-revision":"0".repeat(64)}})) as typeof fetch})).rejects.toThrow("ASSET_RESPONSE_INVALID");});
 it("cancels a real oversized HTTP stream and stops transfer at inventory limit",async()=>{const a=syntheticArtwork("image"),inventory=a.assets[0]!;inventory.bytes=3;inventory.sha256=createHash("sha256").update(new Uint8Array([1,2,3])).digest("hex");const publicationId="a0000000-0000-4000-8000-000000000001",revisionSha256="1".repeat(64),asset={assetId:inventory.id,mime:inventory.mime,url:`/api/v1/publications/${publicationId}/assets/${inventory.id}`};let closed=false;const server=createServer((_req,res)=>{res.writeHead(200,{"content-type":inventory.mime,"x-exhibitos-publication-revision":revisionSha256});res.on("close",()=>{closed=true;});res.write(new Uint8Array(4));});await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const address=server.address();if(!address||typeof address==="string")throw Error("HTTP_TEST_BIND");try{const fetcher=((url,options)=>fetch(`http://127.0.0.1:${address.port}${url}`,options)) as typeof fetch;await expect(fetchVerifiedAsset({publicationId,revisionSha256,asset,inventory,signal:new AbortController().signal,fetcher})).rejects.toThrow("ASSET_INTEGRITY");for(let i=0;i<100&&!closed;i++)await new Promise(r=>setTimeout(r,10));expect(closed).toBe(true);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
 it("interrupts a pending reader on abort and releases the stream",async()=>{const a=syntheticArtwork("image"),inventory=a.assets[0]!;inventory.bytes=3;inventory.sha256="0".repeat(64);const publicationId="a0000000-0000-4000-8000-000000000001",revisionSha256="1".repeat(64),asset={assetId:inventory.id,mime:inventory.mime,url:`/api/v1/publications/${publicationId}/assets/${inventory.id}`},controller=new AbortController();let cancelled=false;const fetcher=(async()=>new Response(new ReadableStream({cancel(){cancelled=true;}}),{headers:{"content-type":inventory.mime,"x-exhibitos-publication-revision":revisionSha256}})) as typeof fetch;const result=fetchVerifiedAsset({publicationId,revisionSha256,asset,inventory,signal:controller.signal,fetcher});await tick();controller.abort();await expect(result).rejects.toMatchObject({name:"AbortError"});expect(cancelled).toBe(true);});

});
