// SPDX-License-Identifier: AGPL-3.0-or-later
import {describe,it,expect} from 'vitest';
import * as three from 'three';
import {centerMetricModel,metricCameraFit,artifactMetricModel} from './metric-model.js';
describe('centred metre-space model framing',()=>{
 it('preserves planar vertex/index/normal bytes and authored transforms with wrapper-only translation',()=>{const source=new three.Group(),mesh=new three.Mesh(new three.PlaneGeometry(1,2),new three.MeshBasicMaterial());mesh.position.set(3,4,5);source.add(mesh);const position=mesh.geometry.getAttribute('position').array.slice(),normal=mesh.geometry.getAttribute('normal').array.slice(),index=mesh.geometry.index!.array.slice();source.updateMatrixWorld();const pose=mesh.matrix.clone();const result=centerMetricModel(three,source);expect(result.measured.size).toEqual([1,2,0]);expect(result.measured.scale).toEqual([1,1,1]);expect(result.object.position.toArray()).toEqual([-3,-4,-5]);expect(mesh.position.toArray()).toEqual([3,4,5]);expect(mesh.geometry.getAttribute('position').array).toEqual(position);expect(mesh.geometry.getAttribute('normal').array).toEqual(normal);expect(mesh.geometry.index!.array).toEqual(index);expect(mesh.matrix.elements).toEqual(pose.elements);const b=new three.Box3().setFromObject(result.object,true);expect(b.min.toArray()).toEqual([-.5,-1,0]);expect(b.max.toArray()).toEqual([.5,1,0]);});
 it('accepts every planar zero-axis orientation and preserves a volumetric model',()=>{for(const rotation of [[0,0,0],[Math.PI/2,0,0],[0,Math.PI/2,0]]){const m=new three.Mesh(new three.PlaneGeometry(1,1),new three.MeshBasicMaterial());m.rotation.set(...rotation as [number,number,number]);expect(centerMetricModel(three,m).extent).toBeCloseTo(1);}const box=new three.Mesh(new three.BoxGeometry(1,2,3),new three.MeshBasicMaterial());expect(centerMetricModel(three,box).measured.size).toEqual([1,2,3]);});
 it('refuses point/line-only empty nonfinite and over-range geometry without changing the source',()=>{for(const values of [[0,0,0,0,0,0,0,0,0],[0,0,0,1,0,0,2,0,0],[NaN,0,0,1,0,0,0,1,0],[10001,0,0,10002,0,0,10001,1,0]]){const g=new three.BufferGeometry();g.setAttribute('position',new three.Float32BufferAttribute(values,3));const m=new three.Mesh(g,new three.MeshBasicMaterial());expect(()=>centerMetricModel(three,m)).toThrow('MODEL_METRIC_BOUNDS');expect(m.parent).toBeNull();}expect(()=>centerMetricModel(three,new three.Group())).toThrow();});
 it('fits camera and zoom without resizing small positive geometry or inventing thickness',()=>{expect(metricCameraFit(1,.5)).toEqual({distance:4.2,near:.20000000000000018,far:8.2});const narrow=metricCameraFit(1,1/360,.5);expect(narrow.distance).toBeCloseTo(1512);expect(narrow.near).toBeLessThan(narrow.distance-1);expect(narrow.far).toBeGreaterThan(narrow.distance+1);expect(metricCameraFit(1,1,3).distance).toBeCloseTo(.7);expect(metricCameraFit(1e-6,1).distance).toBeCloseTo(2.1e-6,12);for(const args of [[0,1],[NaN,1],[1,0],[1,Infinity],[1,1,0],[10001,1]])expect(()=>metricCameraFit(...args as [number,number,number?])).toThrow();});
});

it('artifact affine is outside GLTF centering and does not mutate source bytes or node pose',()=>{
 const geometry=new three.PlaneGeometry(2,2),mesh=new three.Mesh(geometry,new three.MeshBasicMaterial());mesh.position.set(4,5,0);const bytes=geometry.getAttribute('position').array.slice(),matrix=mesh.matrix.clone();mesh.updateMatrix();const before=mesh.matrix.clone();const centered=centerMetricModel(three,mesh),A={position:[1,2,3] as [number,number,number],rotation:[0,0,Math.SQRT1_2,Math.SQRT1_2] as [number,number,number,number],scale:[2,1,1] as [number,number,number]};
 const artifact=artifactMetricModel(three,centered.object,A);expect(artifact.center.toArray()).toEqual([1,2,3]);expect(artifact.measured.size[0]).toBeCloseTo(2);expect(artifact.measured.size[1]).toBeCloseTo(4);expect(artifact.measured.size[2]).toBe(0);expect(geometry.getAttribute('position').array).toEqual(bytes);expect(mesh.matrix.elements).toEqual(before.elements);expect(matrix.elements).not.toEqual(before.elements);
});
