// SPDX-License-Identifier: AGPL-3.0-or-later
import { afterEach, expect, test, vi } from 'vitest';
import { createWalkingInput } from './navigation-input';
afterEach(() => vi.unstubAllGlobals());
function fixture() {
  const doc = Object.assign(new EventTarget(), { activeElement: null as unknown, pointerLockElement: null as unknown, hidden:false, exitPointerLock:vi.fn(() => {doc.pointerLockElement=null;}) });
  const canvas = Object.assign(new EventTarget(), { focus:()=>{doc.activeElement=canvas;}, requestPointerLock:vi.fn<()=>Promise<void> | void>(), getBoundingClientRect:()=>({left:0,width:100}),setPointerCapture:vi.fn() });
  vi.stubGlobal('document',doc);vi.stubGlobal('window',new EventTarget());
  const pause=vi.fn(),error=vi.fn(),input=createWalkingInput(canvas as unknown as HTMLCanvasElement,pause,error);
  input.enable();return {doc,canvas,input,pause,error};
}
test('pending capture after pause then resume releases stale native lock',async()=>{
  const {doc,canvas,input}=fixture();let finish!:()=>void;
  canvas.requestPointerLock.mockImplementation(()=>new Promise<void>(r=>{finish=r;}));
  const pending=input.capture();input.pause();input.enable();doc.pointerLockElement=canvas;finish();await pending;
  expect(doc.exitPointerLock).toHaveBeenCalledOnce();input.dispose();
});
test('disposed pending capture releases native lock and suppresses stale rejection',async()=>{
  const {doc,canvas,input,error}=fixture();let finish!:()=>void;
  canvas.requestPointerLock.mockImplementation(()=>new Promise<void>(r=>{finish=r;}));
  const pending=input.capture();input.dispose();doc.pointerLockElement=canvas;finish();await pending;
  expect(doc.exitPointerLock).toHaveBeenCalledOnce();expect(error).not.toHaveBeenCalled();
});
test('touch movement tokens release independently and pause clears all held movement',()=>{
  const {input}=fixture();input.press('forward',1);input.press('right',2);
  expect(input.sample(.01)).toMatchObject({forward:1,right:1});input.release(1);
  expect(input.sample(.01)).toMatchObject({forward:0,right:1});input.pause();input.enable();
  expect(input.sample(.01)).toMatchObject({forward:0,right:0});input.dispose();
});

test('legacy void capture stays pending until a document failure and reports once', async () => {
  const { doc, canvas, input, error } = fixture();
  canvas.requestPointerLock.mockImplementation(() => undefined);
  let completed = false;
  const pending = input.capture().then(() => { completed = true; });
  await Promise.resolve();
  expect(completed).toBe(false);
  doc.dispatchEvent(new Event('pointerlockerror'));
  await pending;
  expect(error).toHaveBeenCalledOnce();
  doc.dispatchEvent(new Event('pointerlockerror'));
  expect(error).toHaveBeenCalledOnce();
  input.dispose();
});
test('legacy success settles and permits mouse look only with real document lock', async () => {
  const { doc, canvas, input, error } = fixture();
  canvas.requestPointerLock.mockImplementation(() => undefined);
  const pending = input.capture();
  doc.pointerLockElement = canvas;
  doc.dispatchEvent(new Event('pointerlockchange'));
  await pending;
  const move = Object.assign(new Event('mousemove'), { movementX: 10, movementY: 5 });
  window.dispatchEvent(move);
  expect(input.sample(.01)).toMatchObject({ yawDelta: -.02, pitchDelta: -.01 });
  expect(error).not.toHaveBeenCalled();
  input.dispose();
});
test('legacy late success after pause and resume releases stale lock without pausing renewed keyboard input', async () => {
  const { doc, canvas, input, error, pause } = fixture();
  canvas.requestPointerLock.mockImplementation(() => undefined);
  const pending = input.capture();
  input.pause();
  input.enable();
  doc.pointerLockElement = canvas;
  doc.dispatchEvent(new Event('pointerlockchange'));
  await pending;
  expect(doc.exitPointerLock).toHaveBeenCalledOnce();
  expect(error).not.toHaveBeenCalled();
  input.press('forward', 1);
  expect(input.sample(.01).forward).toBe(1);
  expect(pause).toHaveBeenCalledOnce();
  input.dispose();
});
test('legacy pending disposal retains guards until late success and then removes them', async () => {
  const { doc, canvas, input, error } = fixture();
  const remove = vi.spyOn(doc, 'removeEventListener');
  canvas.requestPointerLock.mockImplementation(() => undefined);
  const pending = input.capture();
  input.dispose();
  const before = remove.mock.calls.length;
  doc.pointerLockElement = canvas;
  doc.dispatchEvent(new Event('pointerlockchange'));
  await pending;
  expect(doc.exitPointerLock).toHaveBeenCalledOnce();
  expect(error).not.toHaveBeenCalled();
  expect(remove.mock.calls.length).toBe(before + 2);
});
test('stale legacy rejection after disposal is suppressed', async () => {
  const { doc, canvas, input, error } = fixture();
  canvas.requestPointerLock.mockImplementation(() => undefined);
  const pending = input.capture();
  input.dispose();
  doc.dispatchEvent(new Event('pointerlockerror'));
  await pending;
  expect(error).not.toHaveBeenCalled();
});
test('document error plus Promise rejection reports the same failure once', async () => {
  const { doc, canvas, input, error } = fixture();
  let reject!: (reason: Error) => void;
  canvas.requestPointerLock.mockImplementation(() => new Promise<void>((_, r) => { reject = r; }));
  const pending = input.capture();
  doc.dispatchEvent(new Event('pointerlockerror'));
  reject(new Error('denied'));
  await pending;
  await Promise.resolve();
  expect(error).toHaveBeenCalledOnce();
  input.dispose();
});
test('pending request prevents overlapping native requests even after pause and resume', async () => {
  const { doc, canvas, input } = fixture();
  canvas.requestPointerLock.mockImplementation(() => undefined);
  const pending = input.capture();
  input.pause();
  input.enable();
  await input.capture();
  expect(canvas.requestPointerLock).toHaveBeenCalledOnce();
  doc.dispatchEvent(new Event('pointerlockerror'));
  await pending;
  const retry = input.capture();
  expect(canvas.requestPointerLock).toHaveBeenCalledTimes(2);
  doc.dispatchEvent(new Event('pointerlockerror'));
  await retry;
  input.dispose();
});
test('old Promise completion after event settlement cannot release a newer capture', async () => {
  const { doc, canvas, input } = fixture();
  let oldFinish!: () => void, newFinish!: () => void;
  canvas.requestPointerLock.mockImplementationOnce(() => new Promise<void>(r => { oldFinish = r; })).mockImplementationOnce(() => new Promise<void>(r => { newFinish = r; }));
  const old = input.capture();
  doc.pointerLockElement = canvas;
  doc.dispatchEvent(new Event('pointerlockchange'));
  await old;
  input.pause();
  input.enable();
  const fresh = input.capture();
  doc.pointerLockElement = canvas;
  oldFinish();
  await Promise.resolve();
  expect(doc.pointerLockElement).toBe(canvas);
  expect(doc.exitPointerLock).toHaveBeenCalledOnce();
  newFinish();
  await fresh;
  expect(doc.pointerLockElement).toBe(canvas);
  input.dispose();
});
test('synchronous request failure reports and cleans up so a subsequent request can succeed', async () => {
  const { doc, canvas, input, error } = fixture();
  canvas.requestPointerLock.mockImplementationOnce(() => { throw new Error('unsupported'); }).mockImplementationOnce(() => undefined);
  await input.capture();
  expect(error).toHaveBeenCalledOnce();
  const retry = input.capture();
  doc.pointerLockElement = canvas;
  doc.dispatchEvent(new Event('pointerlockchange'));
  await retry;
  expect(canvas.requestPointerLock).toHaveBeenCalledTimes(2);
  input.dispose();
});
test('queued unlock after explicit pause does not pause a renewed session, while new lock loss does', async () => {
  const { doc, canvas, input, pause } = fixture();
  canvas.requestPointerLock.mockImplementation(() => undefined);
  const pending = input.capture();
  doc.pointerLockElement = canvas;
  doc.dispatchEvent(new Event('pointerlockchange'));
  await pending;
  input.pause();
  input.enable();
  doc.dispatchEvent(new Event('pointerlockchange'));
  input.press('forward', 1);
  expect(input.sample(.01).forward).toBe(1);
  expect(pause).toHaveBeenCalledOnce();
  const fresh = input.capture();
  doc.pointerLockElement = canvas;
  doc.dispatchEvent(new Event('pointerlockchange'));
  await fresh;
  doc.pointerLockElement = null;
  doc.dispatchEvent(new Event('pointerlockchange'));
  expect(input.sample(.01).forward).toBe(0);
  expect(pause).toHaveBeenCalledTimes(2);
  input.dispose();
});
