// SPDX-License-Identifier: AGPL-3.0-or-later
import {validateOpeningClientMessage,validateOpeningServerMessage,type OpeningClientMessage,type OpeningSnapshot,type OpeningParticipant} from '@exhibitos/studio-contract';
import type {PresenceSocket} from './realtime';
import {OpeningVoice,type VoiceStats} from './opening-rtc';
export interface OpeningState {status:'solo'|'connecting'|'joined'|'reconnecting'|'failed';selfId:string|null;phase:'waiting'|'live'|'ended';participants:OpeningParticipant[];messages:OpeningSnapshot['messages'];reports:OpeningSnapshot['reports'];guide:OpeningSnapshot['guide'];chat:boolean;voiceConsent:boolean;follow:boolean;voice:VoiceStats;message:string;blocked:string[]}
interface Options {publicationId:string;revisionSha256:string;viewpointIds:ReadonlySet<string>;origin:string;check:(signal?:AbortSignal)=>Promise<void>;changed:(state:OpeningState)=>void;attachAudio:(audio:HTMLAudioElement)=>void;viewpoint:(id:string)=>void;socket?:(url:string)=>PresenceSocket;fetcher?:typeof fetch;voice?:Partial<ConstructorParameters<typeof OpeningVoice>[0]>}
const initial=():OpeningState=>({status:'solo',selfId:null,phase:'waiting',participants:[],messages:[],reports:[],guide:null,chat:false,voiceConsent:false,follow:false,voice:{peers:0,microphone:false,requesting:false,connected:0,receivedBytes:0,sentBytes:0,message:'음성은 선택해서 허용합니다. 녹음하지 않습니다.'},message:'오프닝은 직접 참여합니다. 혼자·무음 관람은 계속 사용할 수 있습니다.',blocked:[]});
/** Explicit opt-in event socket; host grants and rotating resume secrets live only in private memory. */
export class OpeningSession {
 private socket:PresenceSocket|null=null;private controller:AbortController|null=null;private generation=0;private opted=false;private token:string|undefined;private hostGrant:string|undefined;private microphoneCommand=0;private retries=0;private timer:ReturnType<typeof setTimeout>|undefined;private deadline:ReturnType<typeof setTimeout>|undefined;private lastSequence=-1;private lastTime=0;private seenGuide=-1;private blocked=new Set<string>();private state=initial();private voice:OpeningVoice;
 constructor(private options:Options){this.voice=new OpeningVoice({...options.voice,send:(targetId,body)=>{this.send({version:1,type:'signal',targetId,...body} as OpeningClientMessage);},attach:options.attachAudio,changed:voice=>{this.state.voice=voice;this.emit();}});}
 snapshot(){return structuredClone(this.state);}
 private emit(){this.options.changed(this.snapshot());}
 join(){this.leave();this.opted=true;void this.connect();}
 retry(){this.join();}
 async joinHost(){this.leave();this.opted=true;const generation=++this.generation;this.state.status='connecting';this.state.message='로그인된 호스트 권한을 명시적으로 확인합니다.';this.emit();this.controller=new AbortController();const fetcher=this.options.fetcher??fetch;
  try{const response=await fetcher('/api/v1/auth/session',{credentials:'same-origin',cache:'no-store',signal:this.controller.signal});if(!response.ok)throw Error('HOST_SESSION_REQUIRED');const session=await response.json() as {tenantId?:unknown;csrfToken?:unknown};if(typeof session.tenantId!=='string'||!/^[0-9a-f-]{36}$/.test(session.tenantId)||typeof session.csrfToken!=='string')throw Error('HOST_SESSION_INVALID');
   const grantResponse=await fetcher(`/api/v1/tenants/${session.tenantId}/studio/publications/${this.options.publicationId}/opening-host`,{method:'POST',credentials:'same-origin',cache:'no-store',signal:this.controller.signal,headers:{'content-type':'application/json','x-csrf-token':session.csrfToken},body:JSON.stringify({revisionSha256:this.options.revisionSha256})});if(!grantResponse.ok)throw Error('HOST_FORBIDDEN');const grant=await grantResponse.json() as {hostGrant?:unknown;expiresAt?:unknown};if(typeof grant.hostGrant!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(grant.hostGrant)||typeof grant.expiresAt!=='number'||!Number.isSafeInteger(grant.expiresAt))throw Error('HOST_GRANT_INVALID');if(generation!==this.generation||!this.opted)return;this.hostGrant=grant.hostGrant;await this.connect();
  }catch{if(generation===this.generation)this.fail('호스트 권한이 없거나 로그인되지 않았습니다. 일반 참여와 혼자 관람은 유지됩니다.');}
 }
 private send(message:OpeningClientMessage){if(!validateOpeningClientMessage(message)||this.socket?.readyState!==1)return false;if(this.socket.bufferedAmount>65536){this.fail('오프닝 전송 예산을 초과해 연결과 음성을 정지했습니다.');return false;}try{this.socket.send(JSON.stringify(message));return true;}catch{this.fail('오프닝 전송에 실패해 음성과 연결을 정지했습니다.');return false;}}
 private cleanup(){this.controller?.abort();this.controller=null;if(this.deadline)clearTimeout(this.deadline);this.deadline=undefined;if(this.socket){this.socket.onopen=null;this.socket.onmessage=null;this.socket.onclose=null;this.socket.onerror=null;this.socket.close(1000);this.socket=null;}this.voice.stop();}
 private fail(message:string){++this.generation;this.opted=false;if(this.timer)clearTimeout(this.timer);this.timer=undefined;this.cleanup();this.token=undefined;this.hostGrant=undefined;this.state={...initial(),status:'failed',message};this.emit();}
 private async connect(){const generation=++this.generation;if(!this.opted)return;this.state.status=this.retries?'reconnecting':'connecting';this.emit();this.controller?.abort();this.controller=new AbortController();
  try{await this.options.check(this.controller.signal);if(generation!==this.generation||!this.opted)return;const base=new URL(this.options.origin);if(!['http:','https:'].includes(base.protocol))throw Error('ORIGIN_INVALID');base.protocol=base.protocol==='https:'?'wss:':'ws:';base.pathname=`/api/v1/publications/${this.options.publicationId}/opening`;base.search='';base.hash='';const socket=(this.options.socket??(url=>new WebSocket(url) as unknown as PresenceSocket))(base.toString());this.socket=socket;const current=()=>this.opted&&generation===this.generation&&this.socket===socket;
   socket.onopen=()=>{if(current())this.send({version:1,type:'join',publicationId:this.options.publicationId,revisionSha256:this.options.revisionSha256,...(this.token?{resumeToken:this.token}:this.hostGrant?{hostGrant:this.hostGrant}:{})});};
   socket.onmessage=event=>{if(!current())return;if(typeof event.data!=='string'||event.data.length>65536||new TextEncoder().encode(event.data).length>65536){this.fail('오프닝 메시지 예산을 초과했습니다.');return;}let message:unknown;try{message=JSON.parse(event.data);}catch{this.fail('오프닝 메시지가 손상되었습니다.');return;}if(!validateOpeningServerMessage(message,this.options.publicationId,this.options.revisionSha256,this.options.viewpointIds)){this.fail('오프닝 메시지를 검증할 수 없습니다.');return;}
    if(message.type==='pong')return;if(message.type==='signal'){if(this.state.status==='joined'&&!this.blocked.has(message.fromId)&&message.fromId!==this.state.selfId)void this.voice.signal(message.fromId,message);return;}
    if(message.type==='error'){if(['VOICE_FULL','CONSENT_REQUIRED','HOST_REQUIRED','TARGET_UNAVAILABLE','VIEWPOINT_INVALID'].includes(message.code)){if(message.code==='VOICE_FULL'||message.code==='CONSENT_REQUIRED'){this.state.voiceConsent=false;this.voice.stop();}this.state.message='오프닝 동작이 거부되었습니다: '+message.code;this.emit();}else this.fail('오프닝 접근이 종료되었습니다: '+message.code);return;}
    if(message.type==='snapshot'&&(this.state.status!=='joined'||message.selfId!==this.state.selfId)){this.fail('오프닝 identity가 일치하지 않습니다.');return;}if(message.type==='welcome'&&this.token&&message.selfId!==this.state.selfId){this.fail('재연결 identity가 일치하지 않습니다.');return;}if(message.serverTime<this.lastTime){this.fail('오프닝 시각이 역행했습니다.');return;}if(message.type==='snapshot'&&message.sequence<=this.lastSequence)return;
    if(message.type==='welcome'){this.token=message.resumeToken;this.hostGrant=undefined;if(this.deadline)clearTimeout(this.deadline);this.deadline=undefined;this.state.selfId=message.selfId;this.state.chat=false;this.state.voiceConsent=false;this.state.follow=false;this.send({version:1,type:'preferences',chat:false,voice:false,follow:false});}
    this.lastSequence=message.sequence;this.lastTime=message.serverTime;this.blocked=new Set(message.blockedIds);this.state.blocked=[...this.blocked];this.state.status='joined';this.state.phase=message.phase;this.state.participants=structuredClone(message.participants);this.state.messages=this.state.chat?message.messages.filter(m=>!this.blocked.has(m.participantId)).map(m=>({...m})):[];this.state.reports=structuredClone(message.reports);this.state.guide=structuredClone(message.guide);this.state.message='오프닝에 참여했습니다. 글·음성·따라가기는 각각 허용합니다.';
    const self=message.participants.find(p=>p.id===message.selfId);if(!self?.connected){this.fail('오프닝 참가가 해제되었습니다.');return;}if(self.muted||message.phase==='ended'){this.state.voiceConsent=false;this.voice.stop();}else this.voice.update(message.selfId,message.participants,this.state.voiceConsent,this.blocked);
    if(message.guide&&message.guide.sequence!==this.seenGuide){this.seenGuide=message.guide.sequence;if(this.state.follow&&self.follow)this.options.viewpoint(message.guide.id);}this.emit();
   };
   socket.onclose=()=>{if(!current())return;this.socket=null;this.voice.stop();this.state.chat=false;this.state.voiceConsent=false;this.state.follow=false;this.state.messages=[];this.state.participants=[];if(this.deadline)clearTimeout(this.deadline);this.deadline=undefined;if(this.retries>=3){this.fail('재연결 한도에 도달했습니다. 직접 다시 참여하거나 혼자 관람하세요.');return;}this.retries++;this.state.status='reconnecting';this.state.message='연결이 끊어져 실제 음성을 정지했습니다. 재참여해도 마이크는 자동으로 켜지지 않습니다.';this.emit();this.timer=setTimeout(()=>{this.timer=undefined;void this.connect();},1000*2**(this.retries-1));};socket.onerror=()=>{};
   this.deadline=setTimeout(()=>{if(current())this.fail('오프닝 연결 확인 시간이 초과되었습니다.');},10000);
  }catch{if(generation===this.generation)this.fail('현재 전시나 오프닝 서비스에 접근할 수 없습니다.');}
 }
 preferences(chat:boolean,voice:boolean,follow:boolean){if(this.state.status!=='joined')return;this.state.chat=chat;this.state.voiceConsent=voice;this.state.follow=follow;if(!chat)this.state.messages=[];if(!voice)this.voice.stop();this.send({version:1,type:'preferences',chat,voice,follow});if(this.state.selfId)this.voice.update(this.state.selfId,this.state.participants,voice,this.blocked);this.emit();}
 chat(text:string){if(this.state.chat&&this.state.status==='joined')this.send({version:1,type:'chat',text});}
 block(targetId:string){if(this.state.status!=='joined'||targetId===this.state.selfId||!this.state.participants.some(p=>p.id===targetId)||this.blocked.size>=20)return;this.blocked.add(targetId);this.state.blocked=[...this.blocked];this.state.messages=this.state.messages.filter(m=>m.participantId!==targetId);if(this.state.selfId)this.voice.update(this.state.selfId,this.state.participants,this.state.voiceConsent,this.blocked);this.send({version:1,type:'block',targetId});this.emit();}
 report(targetId:string,reason:'spam'|'abuse'|'other',note:string){this.send({version:1,type:'report',targetId,reason,note});}
 host(command:'begin'|'end'|'guide'|'meet'|'mute_all'|'mute'|'remove',id?:string){if(!this.state.participants.some(p=>p.id===this.state.selfId&&p.host))return;this.send(command==='guide'||command==='meet'?{version:1,type:'host',command,viewpointId:id??''}:command==='mute'||command==='remove'?{version:1,type:'host',command,targetId:id??''}:{version:1,type:'host',command});}
 acceptGuide(){if(this.state.guide&&this.state.status==='joined')this.options.viewpoint(this.state.guide.id);}
 async microphone(enabled:boolean){const generation=this.generation,command=++this.microphoneCommand;try{if(this.state.status!=='joined'||!this.state.voiceConsent)throw Error('VOICE_NOT_CONSENTED');await this.voice.microphone(enabled);}catch{if(generation!==this.generation||command!==this.microphoneCommand)return;await this.voice.microphone(false);this.state.message='마이크 권한이 없거나 음성을 허용하지 않았습니다. 글 대화와 무음 관람을 이용하세요.';this.emit();}}
 retryListening(){if(this.state.voiceConsent)this.voice.retryListening();}
 measureVoice(){if(this.state.status==='joined'&&this.state.voiceConsent)void this.voice.measure();}
 leave(){++this.microphoneCommand;++this.generation;this.opted=false;if(this.timer)clearTimeout(this.timer);this.timer=undefined;if(this.socket?.readyState===1)this.send({version:1,type:'leave'});this.cleanup();this.token=undefined;this.hostGrant=undefined;this.retries=0;this.lastSequence=-1;this.lastTime=0;this.seenGuide=-1;this.blocked.clear();this.state=initial();this.emit();}
 dispose(){this.leave();}
}
