// SPDX-License-Identifier: AGPL-3.0-or-later
import {test,expect} from 'vitest';
import {OpeningSession} from './opening';
import type {PresenceSocket} from './realtime';
const publicationId='11111111-1111-4111-8111-111111111111',selfId='22222222-2222-4222-8222-222222222222',otherId='33333333-3333-4333-8333-333333333333',revision='a'.repeat(64);
const participant=(id=selfId)=>({id,name:'Visitor ABC123',host:false,chat:false,voice:false,follow:false,muted:false,connected:true});
const welcome=()=>({version:1,type:'welcome',publicationId,revisionSha256:revision,selfId,serverTime:1000,sequence:1,phase:'waiting',participants:[participant(),participant(otherId)],guide:null,messages:[],reports:[],blockedIds:[],resumeToken:'a'.repeat(43),resumeExpiresAt:31000});
async function settle(){for(let i=0;i<10;i++)await Promise.resolve();}
function fixture(){const sockets:PresenceSocket[]=[],sent:string[]=[],views:string[]=[];let checks=0,fetches=0,media=0;const session=new OpeningSession({publicationId,revisionSha256:revision,viewpointIds:new Set(['entrance']),origin:'https://example.test',check:async()=>{checks++;},changed:()=>{},attachAudio:()=>{},viewpoint:id=>views.push(id),fetcher:async()=>{fetches++;return new Response('{}',{status:403});},socket:url=>{expect(url).toBe(`wss://example.test/api/v1/publications/${publicationId}/opening`);const socket:PresenceSocket={readyState:1,bufferedAmount:0,send:s=>sent.push(s),close:()=>{},onopen:null,onclose:null,onerror:null,onmessage:null};sockets.push(socket);return socket;},voice:{media:async()=>{media++;throw Error('NOT_ALLOWED');},peer:()=>{throw Error('No default peers');}}});return{session,sockets,sent,views,counts:()=>({checks,fetches,media})};}
async function joined(){const f=fixture();f.session.join();await settle();f.sockets[0]!.onopen?.({});f.sockets[0]!.onmessage?.({data:JSON.stringify(welcome())});return f;}
test('default opening has zero sockets auth probes or microphone and guestjoin sends no role',async()=>{const f=fixture();expect(f.counts()).toEqual({checks:0,fetches:0,media:0});expect(f.sockets).toHaveLength(0);f.session.join();await settle();f.sockets[0]!.onopen?.({});expect(JSON.parse(f.sent[0]!)).toEqual({version:1,type:'join',publicationId,revisionSha256:revision});f.session.dispose();});
test('welcome secrets never enter state and chat listening following remain separate defaultoff',async()=>{const f=await joined();const state=f.session.snapshot();expect(state.chat).toBe(false);expect(state.voiceConsent).toBe(false);expect(state.follow).toBe(false);expect(state.voice.peers).toBe(0);expect(JSON.stringify(state)).not.toContain('resumeToken');f.session.dispose();});
test('guided invitation cannot move without explicitfollow or acceptance; follows only authoredviewpoint',async()=>{const f=await joined();const base=welcome();const snapshot=structuredClone(base) as unknown as Record<string,unknown>;delete snapshot.resumeToken;delete snapshot.resumeExpiresAt;f.sockets[0]!.onmessage?.({data:JSON.stringify({...snapshot,type:'snapshot',sequence:2,guide:{id:'entrance',sequence:1,kind:'meet'}})});expect(f.views).toEqual([]);f.session.acceptGuide();expect(f.views).toEqual(['entrance']);f.session.preferences(false,false,true);f.sockets[0]!.onmessage?.({data:JSON.stringify({...snapshot,type:'snapshot',sequence:3,participants:[{...participant(),follow:true},participant(otherId)],guide:{id:'entrance',sequence:2,kind:'guide'}})});expect(f.views).toEqual(['entrance','entrance']);f.session.dispose();});
test('chat requires consent; hostcommands cannot be locallyasserted by guest; logoutdenial createsnosocket',async()=>{const f=await joined();f.session.chat('denied');expect(f.sent.map(s=>JSON.parse(s)).some(v=>v.type==='chat')).toBe(false);f.session.preferences(true,false,false);f.session.chat('<b>inert authored text</b>');expect(f.sent.map(s=>JSON.parse(s))).toContainEqual({version:1,type:'chat',text:'<b>inert authored text</b>'});f.session.host('begin');expect(f.sent.map(s=>JSON.parse(s)).some(v=>v.type==='host')).toBe(false);f.session.dispose();const host=fixture();await host.session.joinHost();expect(host.counts().fetches).toBe(1);expect(host.sockets).toHaveLength(0);expect(host.session.snapshot().status).toBe('failed');});
test('leave invalidates pendingrightscheck and clears chatmoderation state without startingmic',async()=>{let finish=()=>{},created=0;const session=new OpeningSession({publicationId,revisionSha256:revision,viewpointIds:new Set(),origin:'https://example.test',check:()=>new Promise<void>(resolve=>{finish=resolve;}),changed:()=>{},attachAudio:()=>{},viewpoint:()=>{},socket:()=>{created++;throw Error('Must not connect');}});session.join();session.leave();finish();await settle();expect(created).toBe(0);expect(session.snapshot().status).toBe('solo');expect(session.snapshot().voice.microphone).toBe(false);});
