// SPDX-License-Identifier: AGPL-3.0-or-later
import {useRef,useState} from 'react';
import type {OpeningSession,OpeningState} from './opening';
export function OpeningControls({session,state,offline,viewpoints,audioReady}:{session:OpeningSession|null;state:OpeningState|null;offline:boolean;viewpoints:{id:string;name:string}[];audioReady:(node:HTMLDivElement|null)=>void}) {
 const [text,setText]=useState(''),[note,setNote]=useState(''),[viewpoint,setViewpoint]=useState(viewpoints[0]?.id??'');const sendButton=useRef<HTMLButtonElement>(null);const joined=state?.status==='joined',self=state?.participants.find(p=>p.id===state.selfId),host=!!self?.host;
 return <section aria-label="오프닝과 교육 안내"><h3>오프닝과 교육 안내</h3><p>글·음성·안내 이동은 각각 선택합니다. 녹음하지 않으며 나가면 실제 마이크와 음성 연결을 닫습니다. 글 대화와 정지 관람을 계속 사용할 수 있습니다.</p>
 <button disabled={offline||joined||state?.status==='connecting'} onClick={()=>session?.join()}>오프닝 참여</button><button disabled={offline||joined||state?.status==='connecting'} onClick={()=>{void session?.joinHost();}}>호스트로 참여</button><button disabled={offline||!state||state.status==='solo'} onClick={()=>session?.leave()}>오프닝 나가기</button><button disabled={offline||joined||state?.status==='connecting'} onClick={()=>session?.retry()}>오프닝 다시 참여</button>
 <p role="status">{offline?'오프라인 전시는 오프닝에 연결하지 않습니다.':state?.message}</p>
 <output data-testid="opening-state" data-opening-state={JSON.stringify(state)}>오프닝 {state?.status??'solo'} · {state?.phase??'waiting'} · 역할 {host?'호스트':'방문객'}</output>
 <label><input type="checkbox" disabled={!joined} checked={state?.chat??false} onChange={e=>session?.preferences(e.target.checked,state?.voiceConsent??false,state?.follow??false)}/>글 대화 허용</label>
 <label><input type="checkbox" disabled={!joined||!!self?.muted||state?.phase==='ended'} checked={state?.voiceConsent??false} onChange={e=>session?.preferences(state?.chat??false,e.target.checked,state?.follow??false)}/>음성 듣기 허용 (최대 6명)</label>
 <button disabled={!joined||!state?.voiceConsent||!self?.voice||self.muted} onClick={()=>{void session?.microphone(!(state?.voice.microphone||state?.voice.requesting));}}>{state?.voice.requesting?'마이크 요청 취소':state?.voice.microphone?'마이크 끄기':'마이크 켜기'}</button><button disabled={!state?.voiceConsent} onClick={()=>session?.retryListening()}>음성 듣기 재시도</button>
 <p>{state?.voice.message}</p><output data-testid="opening-voice-state" data-voice-state={JSON.stringify(state?.voice)}>음성 연결 {state?.voice.connected??0} · 마이크 {state?.voice.microphone?'켜짐':'꺼짐'}</output><div ref={audioReady} aria-label="허용한 방문객 음성 재생"/>
 <label><input type="checkbox" disabled={!joined} checked={state?.follow??false} onChange={e=>session?.preferences(state?.chat??false,state?.voiceConsent??false,e.target.checked)}/>안내 따라가기 허용 (저장된 안전한 시점만)</label>
 {state?.guide&&<p>안내 초대: {viewpoints.find(v=>v.id===state.guide!.id)?.name??state.guide.id} · {state.guide.kind}<button disabled={!joined} onClick={()=>session?.acceptGuide()}>안내 초대 위치로 이동</button></p>}
 <form onSubmit={e=>{e.preventDefault();session?.chat(text);setText('');sendButton.current?.focus();}}><label>오프닝 글 대화<input aria-label="오프닝 글 대화" maxLength={240} disabled={!joined||!state?.chat} value={text} onChange={e=>setText(e.target.value)}/></label><button ref={sendButton} disabled={!joined||!state?.chat||!text.trim()}>글 대화 보내기</button></form>
 <ol aria-label="허용한 오프닝 글 대화">{state?.messages.map(m=><li key={m.id}><strong>{m.name}</strong>: {m.text}</li>)}</ol>
 <label>신고 메모<input aria-label="신고 메모" maxLength={240} value={note} onChange={e=>setNote(e.target.value)}/></label>
 <ul aria-label="오프닝 참여자">{state?.participants.map(p=><li key={p.id}>{p.name}{p.id===state.selfId?' (나)':''} · {p.host?'호스트':'방문객'} · {p.muted?'호스트 음소거':p.voice?'음성 허용':'무음'}{p.id!==state.selfId&&<><button disabled={!joined||state.blocked.includes(p.id)} onClick={()=>session?.block(p.id)}>방문객 차단 {p.name}</button><button disabled={!joined} onClick={()=>session?.report(p.id,'other',note)}>방문객 신고 {p.name}</button>{host&&<><button onClick={()=>session?.host('mute',p.id)}>호스트 음소거 {p.name}</button><button onClick={()=>session?.host('remove',p.id)}>호스트 퇴장 {p.name}</button></>}</>}</li>)}</ul>
 {host&&<fieldset><legend>서버가 확인한 호스트 제어</legend><button onClick={()=>session?.host('begin')}>오프닝 시작</button><button onClick={()=>session?.host('end')}>오프닝 종료</button><button onClick={()=>session?.host('mute_all')}>모든 음성 정지</button><label>저장된 안내 시점<select aria-label="저장된 안내 시점" value={viewpoint} onChange={e=>setViewpoint(e.target.value)}>{viewpoints.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><button disabled={!viewpoint} onClick={()=>session?.host('guide',viewpoint)}>선택 시점 안내 초대</button><button disabled={!viewpoint} onClick={()=>session?.host('meet',viewpoint)}>여기에서 만나기 초대</button><ol aria-label="호스트 신고 목록">{state?.reports.map(r=><li key={r.id}>{r.reason} · {r.note}</li>)}</ol></fieldset>}
 <p>직접 음성 연결은 같은 네트워크에서도 방화벽에 따라 실패할 수 있습니다. 외부 중계·STUN/TURN을 사용하지 않습니다. 글 대화 없이도 작품 설명과 대본은 계속 읽을 수 있습니다.</p>
 </section>;
}
