// SPDX-License-Identifier: AGPL-3.0-or-later
import {test,expect} from 'vitest';
import {OpeningVoice} from './opening-rtc';
function fixture(){let mediaCalls=0,created=0,closed=0,audios=0,stopped=0,ice=0;const sends:unknown[]=[];const track={kind:'audio',stop:()=>{stopped++;}} as unknown as MediaStreamTrack;const stream={getTracks:()=>[track],getAudioTracks:()=>[track]} as unknown as MediaStream;let finish:(s:MediaStream)=>void=()=>{};let pending=false;const peers:RTCPeerConnection[]=[];
 const voice=new OpeningVoice({send:(...args)=>sends.push(args),changed:()=>{},attach:()=>{},media:()=>{mediaCalls++;return pending?new Promise(resolve=>{finish=resolve;}):Promise.resolve(stream);},audio:()=>{audios++;return {autoplay:false,controls:false,setAttribute:()=>{},pause:()=>{},remove:()=>{},play:async()=>{},srcObject:null} as unknown as HTMLAudioElement;},peer:()=>{created++;const sender={track:null,replaceTrack:async()=>{}};const pc={connectionState:'new',signalingState:'stable',remoteDescription:null,localDescription:null,onicecandidate:null,ontrack:null,onnegotiationneeded:null,onconnectionstatechange:null,close:()=>{closed++;},addTransceiver:()=>{},getTransceivers:()=>[{receiver:{track:{kind:'audio'}},sender,direction:'recvonly'}],getSenders:()=>[sender],createOffer:async()=>({type:'offer',sdp:'synthetic offer'}),createAnswer:async()=>({type:'answer',sdp:'synthetic answer'}),setLocalDescription:async(d:RTCSessionDescriptionInit)=>{(pc as unknown as {localDescription:RTCSessionDescriptionInit|null}).localDescription=d;},setRemoteDescription:async(d:RTCSessionDescriptionInit)=>{(pc as unknown as {remoteDescription:RTCSessionDescriptionInit|null}).remoteDescription=d;},addIceCandidate:async()=>{ice++;},getStats:async()=>new Map()} as unknown as RTCPeerConnection;peers.push(pc);return pc;}});
 const participants=[{id:'a',voice:true,muted:false,connected:true},{id:'b',voice:true,muted:false,connected:true}];return{voice,participants,peers,sends,stream,pending:(v:boolean)=>{pending=v;},finish:()=>finish(stream),stats:()=>({mediaCalls,created,closed,audios,stopped,ice})};
}
test('default and nonconsenting voice create zero microphone peers or playback resources',()=>{const f=fixture();expect(f.stats()).toMatchObject({mediaCalls:0,created:0,audios:0});f.voice.update('a',f.participants,false,new Set());expect(f.stats()).toMatchObject({mediaCalls:0,created:0,audios:0});});
test('listener consent creates one bounded direct peer but no microphone; block and revoke clean peers',()=>{const f=fixture();f.voice.update('a',f.participants,true,new Set());expect(f.stats()).toMatchObject({created:1,audios:1,mediaCalls:0});f.voice.update('a',f.participants,true,new Set(['b']));expect(f.stats().closed).toBe(1);expect(f.voice.snapshot().peers).toBe(0);f.voice.update('a',f.participants,true,new Set());f.voice.update('a',[{...f.participants[0]!,muted:true,voice:false},f.participants[1]!],true,new Set());expect(f.voice.snapshot().peers).toBe(0);});
test('early ICE is queued until remote description and then applied before answer forwarding',async()=>{const f=fixture();f.voice.update('a',f.participants,true,new Set());await f.voice.signal('b',{candidate:{candidate:'synthetic bounded candidate',sdpMid:'0',sdpMLineIndex:0}});expect(f.stats().ice).toBe(0);await f.voice.signal('b',{description:{type:'offer',sdp:'synthetic offer'}});expect(f.stats().ice).toBe(1);expect(f.sends).toContainEqual(['b',{description:{type:'answer',sdp:'synthetic answer'}}]);f.voice.stop();});
test('explicit microphone permission never occurs on snapshot or reconnect and stop actually stops tracks',async()=>{const f=fixture();f.voice.update('a',f.participants,true,new Set());expect(f.stats().mediaCalls).toBe(0);await f.voice.microphone(true);expect(f.stats().mediaCalls).toBe(1);expect(f.voice.snapshot().microphone).toBe(true);f.voice.stop();expect(f.stats().stopped).toBe(1);f.voice.update('a',f.participants,true,new Set());expect(f.stats().mediaCalls).toBe(1);expect(f.voice.snapshot().microphone).toBe(false);f.voice.stop();});
test('disable microphone while permission pending invalidates late tracks without resurrection',async()=>{const f=fixture();f.pending(true);f.voice.update('a',f.participants,true,new Set());const request=f.voice.microphone(true);await f.voice.microphone(false);f.finish();await request;expect(f.stats().stopped).toBe(1);expect(f.voice.snapshot().microphone).toBe(false);f.voice.stop();});
test('leave while permission pending stops the returned stream and prevents peer restart',async()=>{const f=fixture();f.pending(true);f.voice.update('a',f.participants,true,new Set());const request=f.voice.microphone(true);f.voice.stop();f.finish();await request;expect(f.stats().stopped).toBe(1);expect(f.voice.snapshot().peers).toBe(0);expect(f.voice.snapshot().microphone).toBe(false);});
test('unrecognized or blocked peer signaling has no effect',async()=>{const f=fixture();f.voice.update('a',f.participants,true,new Set(['b']));await f.voice.signal('b',{description:{type:'offer',sdp:'ignored'}});await f.voice.signal('unknown',{candidate:{candidate:'ignored'}});expect(f.sends).toEqual([]);expect(f.stats().ice).toBe(0);});


test('unsupported RTC retains readable fallback instead of throwing from a snapshot',()=>{const voice=new OpeningVoice({send:()=>{},changed:()=>{},attach:()=>{},peer:()=>{throw Error('UNSUPPORTED');}});expect(()=>voice.update('a',[{id:'a',voice:true,muted:false,connected:true},{id:'b',voice:true,muted:false,connected:true}],true,new Set())).not.toThrow();expect(voice.snapshot().peers).toBe(0);expect(voice.snapshot().message).toMatch(/글 대화/);});


test('concurrent microphone clicks retain only latest permission stream and stop superseded tracks',async()=>{
 const resolvers:((stream:MediaStream)=>void)[]=[],stopped=[0,0];const make=(i:number)=>{const track={kind:'audio',stop:()=>{stopped[i]=(stopped[i]??0)+1;}} as unknown as MediaStreamTrack;return {getTracks:()=>[track],getAudioTracks:()=>[track]} as unknown as MediaStream;};
 const voice=new OpeningVoice({send:()=>{},changed:()=>{},attach:()=>{},media:()=>new Promise(resolve=>{resolvers.push(resolve);})});voice.update('a',[{id:'a',voice:true,muted:false,connected:true}],true,new Set());
 const first=voice.microphone(true),second=voice.microphone(true);expect(voice.snapshot().requesting).toBe(true);resolvers[0]!(make(0));await first;expect(stopped).toEqual([1,0]);resolvers[1]!(make(1));await second;expect(voice.snapshot().microphone).toBe(true);expect(voice.snapshot().requesting).toBe(false);voice.stop();expect(stopped).toEqual([1,1]);
});
