// SPDX-License-Identifier: AGPL-3.0-or-later
import {test,expect} from 'vitest';
import {ExhibitionPresence,advancePresenceFrame,parsePresenceMessage,type PresenceSocket} from './realtime';
import {PresenceMotion} from './realtime-motion';
const publicationId='11111111-1111-4111-8111-111111111111',roomId='22222222-2222-4222-8222-222222222222',selfId='33333333-3333-4333-8333-333333333333',remoteId='44444444-4444-4444-8444-444444444444',revision='a'.repeat(64);
const visitor=(id=selfId)=>({visitorId:id,displayName:'Visitor ABC123',roomId,position:[0,1.6,0] as [number,number,number],yaw:0,connected:true});
const welcome=()=>({version:1,type:'welcome',publicationId,revisionSha256:revision,selfId,serverTime:1000,sequence:1,visitors:[visitor(),visitor(remoteId)],resumeToken:'a'.repeat(43),resumeExpiresAt:31000});
async function settle(){for(let i=0;i<5;i++)await Promise.resolve();}
function fixture(){let now=0;const sockets:PresenceSocket[]=[],sent:string[]=[],tasks:{run:()=>void;ms:number;cancelled:boolean}[]=[];let checks=0;const client=new ExhibitionPresence({publicationId,revisionSha256:revision,roomIds:new Set([roomId]),origin:'https://exhibition.example',changed:()=>{},check:async()=>{checks++;},now:()=>now,socket:url=>{expect(url).toBe(`wss://exhibition.example/api/v1/publications/${publicationId}/presence`);const socket:PresenceSocket={readyState:1,bufferedAmount:0,send:data=>sent.push(data),close:()=>{},onopen:null,onclose:null,onmessage:null,onerror:null};sockets.push(socket);return socket;},schedule:(run,ms)=>{tasks.push({run,ms,cancelled:false});return tasks.length as unknown as ReturnType<typeof setTimeout>;},cancel:id=>{const task=tasks[(id as unknown as number)-1];if(task)task.cancelled=true;}});return{client,sockets,sent,tasks,now:(v:number)=>{now=v;},checks:()=>checks};}
async function joined(){const f=fixture();f.client.join();await settle();f.sockets[0]!.onopen?.({});f.sockets[0]!.onmessage?.({data:JSON.stringify(welcome())});return f;}
test('default solo has zero sockets/checks and explicit join sends closed identity-free ABI',async()=>{const f=fixture();expect(f.sockets).toHaveLength(0);expect(f.checks()).toBe(0);f.client.join();await settle();f.sockets[0]!.onopen?.({});expect(JSON.parse(f.sent[0]!)).toEqual({version:1,type:'join',publicationId,revisionSha256:revision});f.client.leave();expect(f.client.snapshot().status).toBe('solo');expect(f.client.avatars()).toEqual([]);});
test('strict inbound snapshot guards binary oversize duplicate self unknown type and revision',()=>{const rooms=new Set([roomId]),valid=welcome();expect(parsePresenceMessage(JSON.stringify(valid),publicationId,revision,rooms)).not.toBeNull();for(const value of [new Uint8Array(4),'a'.repeat(65537),JSON.stringify({...valid,type:'execute'}),JSON.stringify({...valid,revisionSha256:'b'.repeat(64)}),JSON.stringify({...valid,visitors:[visitor(),visitor()]}),JSON.stringify({...valid,visitors:[visitor(remoteId)]}),JSON.stringify({...valid,visitors:[{...visitor(),displayName:'<script>'}]}),JSON.stringify({...valid,extra:true})])expect(parsePresenceMessage(value,publicationId,revision,rooms)).toBeNull();});
test('welcome secret stays out of UI state, outgoing pose has no submitted visitor identity and10Hz cap',async()=>{const f=await joined();expect(JSON.stringify(f.client.snapshot())).not.toContain('resumeToken');expect(f.client.avatars()).toHaveLength(1);f.client.pose(roomId,[0,1.6,0],0);f.now(50);f.client.pose(roomId,[.1,1.6,0],0);f.now(100);f.client.pose(roomId,[.2,1.6,0],0);const poses=f.sent.map(s=>JSON.parse(s)).filter(s=>s.type==='pose');expect(poses).toHaveLength(2);expect(Object.keys(poses[0]).sort()).toEqual(['position','roomId','seq','type','version','yaw']);f.client.dispose();});
test('unexpected disconnect reconnect uses memory token, rotates welcome and preserves self identity',async()=>{const f=await joined();f.sockets[0]!.onclose?.({code:1006});expect(f.client.snapshot().status).toBe('reconnecting');expect(f.client.avatars()).toEqual([]);const retry=f.tasks.find(t=>t.ms===1000&&!t.cancelled)!;retry.run();await settle();f.sockets[1]!.onopen?.({});expect(JSON.parse(f.sent.at(-1)!).resumeToken).toBe('a'.repeat(43));f.sockets[1]!.onmessage?.({data:JSON.stringify({...welcome(),resumeToken:'b'.repeat(43),serverTime:2000,sequence:2})});expect(f.client.snapshot().selfId).toBe(selfId);expect(f.client.snapshot().status).toBe('joined');f.client.dispose();});
test('bounded three reconnect attempts stops even with welcome/close flapping',async()=>{const f=await joined();for(let i=0;i<3;i++){f.sockets[i]!.onclose?.({code:1006});const retry=f.tasks.find(t=>t.ms===1000*2**i&&!t.cancelled)!;retry.cancelled=true;retry.run();await settle();f.sockets[i+1]!.onopen?.({});f.sockets[i+1]!.onmessage?.({data:JSON.stringify({...welcome(),serverTime:2000+i,sequence:2+i})});}f.sockets[3]!.onclose?.({code:1006});expect(f.client.snapshot().status).toBe('failed');expect(f.client.avatars()).toEqual([]);expect(f.client.snapshot().attempts).toBe(3);});
test('leave cancels waiting retry and stale callback cannot reconnect or repopulate avatars',async()=>{const f=await joined();const stale=f.sockets[0]!.onmessage!;f.sockets[0]!.onclose?.({code:1006});const retry=f.tasks.find(t=>t.ms===1000&&!t.cancelled)!;f.client.leave();expect(retry.cancelled).toBe(true);retry.run();stale({data:JSON.stringify(welcome())});await settle();expect(f.sockets).toHaveLength(1);expect(f.client.snapshot().status).toBe('solo');expect(f.client.avatars()).toEqual([]);});
test('forged self snapshot and revoked publication error clear remotes and fall back to solo content',async()=>{for(const message of [{...welcome(),type:'snapshot',selfId:remoteId,resumeToken:undefined,resumeExpiresAt:undefined},{version:1,type:'error',code:'PUBLICATION_UNAVAILABLE'}]){const f=await joined();f.sockets[0]!.onmessage?.({data:JSON.stringify(message)});expect(f.client.snapshot().status).toBe('failed');expect(f.client.snapshot().visitors).toEqual([]);expect(f.client.avatars()).toEqual([]);}});
test('remote interpolation shortest yaw does not extrapolate and respects reduced motion or teleport',()=>{const m=new PresenceMotion();m.update([visitor(remoteId)],0);m.update([{...visitor(remoteId),position:[1,1.6,0],yaw:Math.PI}],100);expect(m.sample(150)[0]!.position[0]).toBe(.5);expect(m.sample(150,true)[0]!.position[0]).toBe(1);expect(m.sample(10000)[0]!.position[0]).toBe(1);m.update([{...visitor(remoteId),position:[10,1.6,0]}],200);expect(m.sample(200)[0]!.position[0]).toBe(10);m.clear();expect(m.sample(200)).toEqual([]);});

test('leave during pending publication check prevents later socket creation',async()=>{let finish=()=>{};let created=0;const client=new ExhibitionPresence({publicationId,revisionSha256:revision,roomIds:new Set([roomId]),origin:'https://exhibition.example',changed:()=>{},check:()=>new Promise<void>(resolve=>{finish=resolve;}),socket:()=>{created++;throw Error('Must not connect');}});client.join();client.leave();finish();await settle();expect(created).toBe(0);expect(client.snapshot().status).toBe('solo');});
test('publication denial and excessive send buffer preserve solo without outgoing movement',async()=>{const denied=new ExhibitionPresence({publicationId,revisionSha256:revision,roomIds:new Set([roomId]),origin:'https://exhibition.example',changed:()=>{},check:async()=>{throw Error('REVOKED');},socket:()=>{throw Error('Must not connect');}});denied.join();await settle();expect(denied.snapshot().status).toBe('failed');expect(denied.avatars()).toEqual([]);const f=await joined();f.sockets[0]!.bufferedAmount=65537;f.client.pose(roomId,[0,1.6,0],0);expect(f.client.snapshot().status).toBe('failed');expect(f.sent.map(v=>JSON.parse(v)).some(v=>v.type==='pose')).toBe(false);});


test('default solo and disconnected presence frames cause no avatar redraw or pose work',async()=>{
 const f=fixture();let renders=0;const scene={update:()=>{renders++;}},pose={roomId,position:[0,1.6,0] as [number,number,number],yaw:0};
 for(let i=0;i<20;i++)advancePresenceFrame(f.client,scene,pose,false);expect(renders).toBe(0);expect(f.sent).toEqual([]);
 f.client.join();await settle();advancePresenceFrame(f.client,scene,pose,false);expect(renders).toBe(0);
 f.sockets[0]!.onmessage?.({data:JSON.stringify(welcome())});advancePresenceFrame(f.client,scene,pose,false);expect(renders).toBe(1);
 f.client.leave();advancePresenceFrame(f.client,scene,pose,false);expect(renders).toBe(1);
});
