// SPDX-License-Identifier: AGPL-3.0-or-later
import {useState,useEffect,useRef} from 'react';
import type {Exhibition} from '@exhibitos/spec';
import {DAYLIGHT_NAMESPACE,TEMPLATE_NAMESPACE,daylightFor,type Daylight,type TemplateProvenance} from '@exhibitos/studio-contract';
import {curvedWall,staircase,ramp,appendArchitecture} from './geometry/advanced';
import {bundledTemplate,duplicateTemplate,validateTemplate,readTemplateFile} from './geometry/templates';
export function AdvancedArchitectureEditor({document,onChange,disabled}:{document:Exhibition;onChange:(e:Exhibition)=>void;disabled:boolean}){
 const [roomId,setRoomId]=useState(document.rooms[0]?.id??''),[kind,setKind]=useState('curve'),[width,setWidth]=useState(2),[rise,setRise]=useState(.2),[run,setRun]=useState(.4),[count,setCount]=useState(4),[radius,setRadius]=useState(2),[sweep,setSweep]=useState(90),[height,setHeight]=useState(3),[error,setError]=useState('');
 const pendingImport=useRef(0),active=useRef(true),current=useRef({document,disabled});current.current={document,disabled};
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const daylight=daylightFor(document)??{version:1,date:'2026-06-21',hour:12,latitude:37.5,northDegrees:0,intensity:1,enabled:false} as Daylight;
 const provenance=document.extensions?.[TEMPLATE_NAMESPACE] as unknown as TemplateProvenance|undefined;
 const work=(f:()=>void)=>{try{f();setError('');}catch(e){setError(e instanceof Error?e.message:'입력 오류');}};
 const setDaylight=(d:Daylight)=>work(()=>onChange({...document,extensions:{...document.extensions,[DAYLIGHT_NAMESPACE]:d as unknown as NonNullable<Exhibition['extensions']>[string]}}));
 const setLicense=(license:TemplateProvenance['license'])=>work(()=>onChange({...document,extensions:{...document.extensions,[TEMPLATE_NAMESPACE]:{version:1,name:document.title,creator:'Local author',source:'bundled:local-author',modified:true,profile:'oes-rectangles-v1',...provenance,license}}}));
 return <section aria-label="고급 건축과 template"><h3>고급 건축 · template</h3><p role="alert">{error}</p><fieldset disabled={disabled}><legend>곡선벽 · 계단 · 접근 경사로</legend>
 <label>건축 대상 방<select aria-label="건축 대상 방" value={document.rooms.some(r=>r.id===roomId)?roomId:document.rooms[0]?.id??''} onChange={e=>setRoomId(e.target.value)}>{document.rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>건축 유형<select aria-label="건축 유형" value={kind} onChange={e=>setKind(e.target.value)}><option value="curve">곡선벽</option><option value="stairs">계단</option><option value="ramp">접근 경사로</option></select></label>
 {(kind==='curve'? [['반경',radius,setRadius],['호 각도',sweep,setSweep],['벽 높이',height,setHeight],['구간 수',count,setCount]]:[['폭',width,setWidth],['단차 또는 총 상승',rise,setRise],['디딤 또는 총 길이',run,setRun],...(kind==='stairs'?[['계단 수',count,setCount]]:[])]).map(([name,value,set])=><label key={String(name)}>{String(name)}<input type="number" step="0.1" value={Number.isFinite(value as number)?value as number:''} onChange={e=>(set as (n:number)=>void)(e.target.value===''?NaN:Number(e.target.value))}/></label>)}
 <button onClick={()=>work(()=>{const room=document.rooms.find(r=>r.id===roomId)??document.rooms[0];if(!room)throw Error('대상 방을 선택하세요.');onChange(appendArchitecture(document,kind==='curve'?curvedWall(room,radius,sweep,count,height):kind==='stairs'?staircase(room,width,rise,run,count):ramp(room,width,rise,run)));})}>건축 추가</button>
 <p>방 좌표의 원점에서 생성하며 각 평면을 기존 표면 편집으로 이동·회전·삭제할 수 있습니다. 곡선벽은 명시적 분할 평면입니다. 계단은 접근 가능한 경로로 간주하지 않으며 별도 경사로·연결 동선을 검사하세요.</p></fieldset>
 <fieldset disabled={disabled}><legend>자연광 시각 근사</legend><label><input type="checkbox" checked={daylight.enabled} onChange={e=>setDaylight({...daylight,enabled:e.target.checked})}/>자연광 사용</label><label>날짜<input type="date" value={daylight.date} onChange={e=>setDaylight({...daylight,date:e.target.value})}/></label>{(['hour','latitude','northDegrees','intensity'] as const).map(k=><label key={k}>{k}<input aria-label={`자연광 ${k}`} type="number" step="0.1" value={daylight[k]} onChange={e=>setDaylight({...daylight,[k]:Number(e.target.value)})}/></label>)}<p>입력 시간은 태양시입니다. 창문은 실제 개구부이며 조명은 태양 방향의 시각 근사입니다. 기상·유리 투과·lux·실제 실내 조도나 건축 접근성 적합성을 보장하지 않습니다.</p></fieldset>
 <fieldset disabled={disabled}><legend>건축 template 복제 · 가져오기 · 저장</legend><p>현재 작품이 없는 draft에 적용합니다. 작품 bytes·오디오·개인 주석은 template에 포함할 수 없습니다. 적용은 undo 가능하며 기존 Studio 로컬 자동 저장·JSON 복구·서버 공개를 사용합니다.</p>
 <button onClick={()=>work(()=>onChange(duplicateTemplate(bundledTemplate(),document)))}>두 방 template 복제</button>
 <label>Template JSON 가져오기<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(!file)return;const request=++pendingImport.current;void(async()=>{try{const captured=document,isCurrent=()=>active.current&&!current.current.disabled&&current.current.document===captured&&request===pendingImport.current;const next=await readTemplateFile(file,captured,isCurrent);if(isCurrent()){onChange(next);setError('');}}catch(problem){if(active.current&&request===pendingImport.current)setError(problem instanceof Error?problem.message:'Template 오류');}})();e.target.value='';}}/></label>
 <p>출처: {provenance?.source??'없음'} · 저작자: {provenance?.creator??'없음'} · license: {provenance?.license??'없음'} · 변경: {String(provenance?.modified??false)}</p>
 {!provenance&&<><button onClick={()=>setLicense('private')}>내 건축을 private template로 지정</button><button onClick={()=>setLicense('CC0-1.0')}>내 건축을 CC0로 지정</button><p>본인이 권리를 가진 건축에만 적용하세요. 가져온 template의 기존 저작자·출처·라이선스를 덮어쓰지 않습니다.</p></>}
 <button onClick={()=>work(()=>{validateTemplate(document,true);const text=JSON.stringify(document,null,2);if(new TextEncoder().encode(text).length>262144)throw Error('Template 최대256KiB');const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=window.document.createElement('a');a.href=url;a.download='exhibitos-architecture-template.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>Template JSON 저장</button><p>재배포 license가 없는 template의 저장·공개·OEX export는 차단됩니다. private draft의 일반 로컬 백업은 계속 사용할 수 있습니다.</p></fieldset></section>;
}
