// SPDX-License-Identifier: AGPL-3.0-or-later
import {describe,it,expect} from 'vitest';
import {CURATION_NAMESPACE,curationFor,validateViewerCuration,curationDurationValid} from './curation.js';
import {EXPERIENCE_NAMESPACE} from './experience.js';
const source='10000000-0000-4000-8000-000000000001';
const fixture=()=>({placements:[{id:source}],mediaAssets:[{id:'media'}],audioZones:[{id:'zone'}],annotations:[{id:'annotation',text:'Original'}],navigation:[{id:'route',waypoints:[{roomId:'room',position:[0,1,0]}]}],extensions:{[EXPERIENCE_NAMESPACE]:{version:1,footsteps:[],voices:[{placementId:source,assetId:'media',locale:'en',transcript:source}],annotations:[],rooms:[],translations:[]},[CURATION_NAMESPACE]:{version:1,audioZones:[{zoneId:'zone',referenceDistance:1,maxDistance:20,rolloff:1,occlusion:{enabled:true,closedGain:0.2}}],transcripts:[{placementId:source,locale:'en',durationSeconds:2,cues:[{start:0,end:1,text:source}],translations:[{locale:'ko',cues:[{start:0,end:1,text:'번역'}]}]}],annotationTranslations:[{annotationId:'annotation',locale:'ko',text:'번역'}],routes:[{routeId:'route',stops:[{waypointIndex:0,title:source,description:'Stationary view',placementId:source}]}]}}});
describe('bounded spatial curation profile',()=>{
 it('keeps absent profile backwards compatible and fresh defaults',()=>{expect(validateViewerCuration({}).valid).toBe(true);const x=curationFor({});x.routes.push({routeId:'a',stops:[]});expect(curationFor({}).routes).toEqual([]);});
 it('retains full original text and independent cues/translations without mutation',()=>{const e=fixture(),before=structuredClone(e);expect(validateViewerCuration(e).valid).toBe(true);const c=curationFor(e);c.transcripts[0]!.cues[0]!.text='changed';expect(e).toEqual(before);expect(e.extensions[EXPERIENCE_NAMESPACE].voices[0]!.transcript).toBe(source);});
 it('rejects unknown version or fields',()=>{for(const change of [(c:Record<string,unknown>)=>c.version=2,(c:Record<string,unknown>)=>c.secret='private']){const e=fixture();change(e.extensions[CURATION_NAMESPACE]);expect(validateViewerCuration(e).valid).toBe(false);}});
 it('rejects negative, reversed, overlapping and out-of-duration timings',()=>{for(const cue of [{start:-1,end:1,text:'x'},{start:1,end:1,text:'x'},{start:0,end:3,text:'x'}]){const e=fixture();e.extensions[CURATION_NAMESPACE].transcripts[0]!.cues=[cue];expect(validateViewerCuration(e).valid).toBe(false);}const e=fixture();e.extensions[CURATION_NAMESPACE].transcripts[0]!.cues.push({start:0.5,end:1.5,text:'overlap'});expect(validateViewerCuration(e).valid).toBe(false);});
 it('rejects exact ID aliases and incompatible voice locale',()=>{const e=fixture();e.extensions[CURATION_NAMESPACE].transcripts[0]!.placementId=source.replace('a','A')+'x';expect(validateViewerCuration(e).valid).toBe(false);const f=fixture();f.extensions[CURATION_NAMESPACE].transcripts[0]!.locale='ko';expect(validateViewerCuration(f).valid).toBe(false);});
 it('rejects translations replacing the source locale and duplicate locale aliases',()=>{const e=fixture();e.extensions[CURATION_NAMESPACE].transcripts[0]!.translations[0]!.locale='EN';expect(validateViewerCuration(e).valid).toBe(false);const f=fixture();f.extensions[CURATION_NAMESPACE].annotationTranslations.push({...f.extensions[CURATION_NAMESPACE].annotationTranslations[0]!,locale:'KO'});expect(validateViewerCuration(f).valid).toBe(false);});
 it('rejects missing, reordered or surplus guided stops and unknown placements',()=>{const e=fixture();e.extensions[CURATION_NAMESPACE].routes[0]!.stops[0]!.waypointIndex=1;expect(validateViewerCuration(e).valid).toBe(false);const f=fixture();f.extensions[CURATION_NAMESPACE].routes[0]!.stops=[];expect(validateViewerCuration(f).valid).toBe(false);const g=fixture();g.extensions[CURATION_NAMESPACE].routes[0]!.stops[0]!.placementId='unknown';expect(validateViewerCuration(g).valid).toBe(false);});
 it('fails closed on distance, attenuation and metadata count bounds',()=>{for(const n of [NaN,Infinity,-1,1001]){const e=fixture();e.extensions[CURATION_NAMESPACE].audioZones[0]!.maxDistance=n;expect(validateViewerCuration(e).valid).toBe(false);}const e=fixture();e.extensions[CURATION_NAMESPACE].audioZones[0]!.occlusion.closedGain=1.1;expect(validateViewerCuration(e).valid).toBe(false);const f=fixture();f.extensions[CURATION_NAMESPACE].transcripts[0]!.cues=Array.from({length:129},()=>({start:0,end:1,text:'x'}));expect(validateViewerCuration(f).valid).toBe(false);});
 it('rejects malformed cross-profile arrays without throwing at the server boundary',()=>{
  for(const name of ['voices','annotations','rooms','footsteps','translations'])for(const value of [[null],null,{},'malformed']){
   const e=fixture();(e.extensions[EXPERIENCE_NAMESPACE] as Record<string,unknown>)[name]=value;
   expect(()=>validateViewerCuration(e)).not.toThrow();expect(validateViewerCuration(e).valid).toBe(false);
  }
  const e=fixture();(e.extensions[EXPERIENCE_NAMESPACE] as Record<string,unknown>).version=2;
  expect(validateViewerCuration(e).valid).toBe(false);
 });
 it('binds declared timing to approved PCM duration, not authored claims',()=>{const e=fixture();expect(curationDurationValid(e,'media',2)).toBe(true);expect(curationDurationValid(e,'media',1)).toBe(false);expect(curationDurationValid(e,'other',1)).toBe(true);});
});
