// SPDX-License-Identifier: AGPL-3.0-or-later
import {test,expect} from 'vitest';
import {spatialAudioWithoutTranscript,SPATIAL_NAMESPACE,validateSpatialProfile,spatialProgramFor,spatialScopeFor,remapSpatialProgram} from './scripting-profile.js';
import type {SpatialProgram} from './scripting.js';
const room='50000000-0000-4000-8000-000000000010',light='50000000-0000-4000-8000-000000000050';
const program=():SpatialProgram=>({version:1,rules:[{id:'author-name',once:false,trigger:{type:'room_enter',roomId:room},actions:[{type:'set_light',lightId:light,multiplier:.4,delayMs:0}]}]});
const scene=()=>({rooms:[{id:room}],audioZones:[],placements:[],lights:[{id:light}],mediaAssets:[],extensions:{[SPATIAL_NAMESPACE]:program()}});
test('optional profile validates exact scene identity and preserves no-behavior absence',()=>{const e=scene();expect(validateSpatialProfile(e).valid).toBe(true);expect(spatialScopeFor(e).rooms.has(room)).toBe(true);expect(spatialProgramFor({}).rules).toEqual([]);expect(validateSpatialProfile({}).valid).toBe(true);e.extensions[SPATIAL_NAMESPACE].rules[0]!.actions=[{type:'play_audio',mediaAssetId:room,volume:1,delayMs:0}];expect(validateSpatialProfile(e).valid).toBe(false);});
test('embedded profile rejects unsupported version and16KiB despite standalone32KiB bound',()=>{const e=scene();(e.extensions[SPATIAL_NAMESPACE] as {version:number}).version=2;expect(validateSpatialProfile(e).valid).toBe(false);e.extensions[SPATIAL_NAMESPACE]=program();e.extensions[SPATIAL_NAMESPACE].rules[0]!.actions=Array.from({length:5},()=>({type:'show_text' as const,text:'x'.repeat(3500),locale:'en',delayMs:0}));expect(validateSpatialProfile(e).errors[0]?.code).toBe('SPATIAL_PROFILE_LIMIT');});
test('program reads are independent copies and remap changes only typed references',()=>{const e=scene(),p=spatialProgramFor(e);p.rules[0]!.id='changed';expect(spatialProgramFor(e).rules[0]!.id).toBe('author-name');const source=program();source.rules[0]!.actions.push({type:'show_text',text:room,locale:'en',delayMs:0},{type:'emit_event',name:'author-name',delayMs:0});const mapped=remapSpatialProgram(source,id=>id===room?'room-new':'light-new');expect(mapped.rules[0]!.trigger).toEqual({type:'room_enter',roomId:'room-new'});expect(mapped.rules[0]!.id).toBe('author-name');expect(mapped.rules[0]!.actions[1]).toMatchObject({text:room});expect(mapped.rules[0]!.actions[2]).toMatchObject({name:'author-name'});expect(source.rules[0]!.trigger).toEqual({type:'room_enter',roomId:room});});

test('script audio publication policy requires original zone or voice text for each exact target',()=>{const e=scene(),id='50000000-0000-4000-8000-000000000070';const candidate={...e,mediaAssets:[{id}],audioZones:[],extensions:{...e.extensions,[SPATIAL_NAMESPACE]:{version:1,rules:[{id:'audio',once:false,trigger:{type:'exhibition_start'},actions:[{type:'play_audio',mediaAssetId:id,volume:1,delayMs:0}]}]}}};expect(spatialAudioWithoutTranscript(candidate)).toEqual([id]);expect(spatialAudioWithoutTranscript({...candidate,audioZones:[{id:room,assetId:id,transcript:'Readable original'}]})).toEqual([]);expect(spatialAudioWithoutTranscript({...candidate,extensions:{...candidate.extensions,'org.exhibitos.viewer/experience':{voices:[{assetId:id,transcript:'Original voice'}]}}})).toEqual([]);expect(spatialAudioWithoutTranscript({...candidate,audioZones:[{id:room,assetId:id,transcript:'  '}]})).toEqual([id]);});
