// SPDX-License-Identifier: AGPL-3.0-or-later
export const LOD_NAMESPACE="org.exhibitos.viewer/lod";
export interface LodVariant {assetId:string;detail:"coarse"|"full";triangles?:number;textureSize?:number}
export interface ViewerLod {version:1;variants:LodVariant[]}
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
export function validateViewerLod(artwork:unknown){const errors:{code:string;path:string;message:string}[]=[];const fail=(message:string)=>errors.push({code:"VIEWER_LOD_INVALID",path:"/extensions/org.exhibitos.viewer~1lod",message});if(!object(artwork)||!object(artwork.extensions)||!Object.hasOwn(artwork.extensions,LOD_NAMESPACE))return {valid:true,errors};const v=artwork.extensions[LOD_NAMESPACE];if(!object(v)||v.version!==1||Object.keys(v).length!==2||!Array.isArray(v.variants)||v.variants.length<1||v.variants.length>2){fail("Expected LOD version 1 with one full and optional coarse variant");return {valid:false,errors};}
 const inventory=Array.isArray(artwork.assets)?artwork.assets.filter(object):[],seen=new Set<string>();let full:Record<string,unknown>|undefined,coarse:Record<string,unknown>|undefined;
 for(const item of v.variants){if(!object(item)||typeof item.assetId!=="string"||!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(item.assetId)||!["coarse","full"].includes(String(item.detail))){fail("Expected a declared asset ID and coarse/full detail");continue;}const asset=inventory.find(a=>typeof a.id==="string"&&a.id.toLowerCase()===(item.assetId as string).toLowerCase());const metric=artwork.artworkType==="image"?"textureSize":"triangles",limit=metric==="textureSize"?8192:1000000;if(!asset||asset.mime!==(artwork.artworkType==="image"?"image/png":"model/gltf-binary")||asset.role!==(artwork.artworkType==="image"?"image":"model")||Object.keys(item).length!==3||!Number.isSafeInteger(item[metric])||Number(item[metric])<1||Number(item[metric])>limit||seen.has(item.assetId.toLowerCase()))fail("Variant must uniquely reference declared same-kind asset and one bounded metric");seen.add(item.assetId.toLowerCase());if(item.detail==="full"){if(full||item.assetId.toLowerCase()!==String(artwork.primaryAssetId).toLowerCase())fail("Exactly one full variant must reference primaryAssetId");full=item;}else{if(coarse)fail("Only one coarse variant is supported");coarse=item;}}
 if(!full)fail("Full primary variant is required");if(coarse&&full){const metric=artwork.artworkType==="image"?"textureSize":"triangles",low=inventory.find(a=>String(a.id).toLowerCase()===String(coarse!.assetId).toLowerCase()),high=inventory.find(a=>String(a.id).toLowerCase()===String(full!.assetId).toLowerCase());if(Number(coarse[metric])>=Number(full[metric])||!Number.isSafeInteger(low?.bytes)||!Number.isSafeInteger(high?.bytes)||Number(low?.bytes)<1||Number(low?.bytes)>=Number(high?.bytes))fail("Coarse variant must reduce both declared detail and actual bytes");}try{if(new TextEncoder().encode(JSON.stringify(v)).length>4096)fail("LOD extension exceeds 4 KiB");}catch{fail("LOD extension must be finite JSON metadata");}return {valid:errors.length===0,errors};}
export function lodVariantsFor(artwork:{primaryAssetId:string;extensions?:unknown}):LodVariant[]{const validation=validateViewerLod(artwork);if(!validation.valid)throw Error("VIEWER_LOD_INVALID");const value=object(artwork.extensions)?artwork.extensions[LOD_NAMESPACE]:undefined;return value?structuredClone((value as unknown as ViewerLod).variants):[{assetId:artwork.primaryAssetId,detail:"full"}];}
