// SPDX-License-Identifier: AGPL-3.0-or-later
import type {FastifyInstance} from 'fastify';
import type {IncomingMessage} from 'node:http';
import type {Duplex} from 'node:stream';
import {randomUUID,randomBytes,createHash} from 'node:crypto';
import {WebSocket,WebSocketServer} from 'ws';
import {validateExhibition} from '@exhibitos/spec';
import {presentationFor,validateStudioPresentation,validateOpeningClientMessage,type OpeningParticipant,type OpeningChat,type OpeningReport,type OpeningClientMessage,type OpeningErrorCode,type OpeningSnapshot} from '@exhibitos/studio-contract';
import type {RealtimePublication} from './realtime.ts';
export interface OpeningSubject {userId:string;tenantId:string;sessionId:string}
export interface OpeningSettings {origin:string;publication(id:string):Promise<RealtimePublication>;authorizeHost(subject:OpeningSubject,publicationId:string):Promise<boolean>}
interface Member {state:OpeningParticipant;socket?:WebSocket;tokenHash:string;expires:number;reservedUntil:number;blocks:Set<string>;reports:number[];subject?:OpeningSubject;chatAt:number;signalTokens:number;signalAt:number}
interface Room {id:string;revision:string;members:Map<string,Member>;viewpoints:Set<string>;phase:OpeningSnapshot['phase'];guide:OpeningSnapshot['guide'];sequence:number;messages:OpeningChat[];reports:OpeningReport[];checkedAt:number;checking?:Promise<boolean>;closed:boolean}
interface Context {socket:WebSocket;pubId:string;room?:Room;member?:Member;alive:boolean;joined:boolean;busy:boolean;queue:Array<{bytes:Buffer;binary:boolean}>;tokens:number;at:number;timer:ReturnType<typeof setTimeout>;pongAt:number}
const hash=(s:string)=>createHash('sha256').update(s).digest('hex'),token=()=>randomBytes(32).toString('base64url'),frame=32768,ttl=1800000;
/** Ephemeral moderated opening rooms; existing publication and authenticated session authorities remain mandatory. */
export function registerOpening(app:FastifyInstance,settings:OpeningSettings){
 const origin=new URL(settings.origin);if(origin.origin!==settings.origin||!['http:','https:'].includes(origin.protocol))throw Error('Exact opening origin required');
 const wss=new WebSocketServer({noServer:true,maxPayload:frame,perMessageDeflate:false}),rooms=new Map<string,Room>(),contexts=new Set<Context>(),grants=new Map<string,{pubId:string;subject:OpeningSubject;expires:number}>(),pending=new Map<string,Promise<unknown>>(),ips=new Map<string,{tokens:number;at:number}>();let stopping=false,lastPing=Date.now();
 const stats={joins:0,signals:0,chats:0,reports:0,policyFailures:0,backpressureDisconnects:0};
 function send(ws:WebSocket,v:unknown){if(ws.readyState!==WebSocket.OPEN)return;const s=JSON.stringify(v);if(ws.bufferedAmount+Buffer.byteLength(s)>65536){stats.backpressureDisconnects++;ws.terminate();return;}ws.send(s,error=>{if(error)ws.terminate();});}
 function error(c:Context,code:OpeningErrorCode,close=false){send(c.socket,{version:1,type:'error',code});if(close)c.socket.close(1008);}
 async function bounded<T>(key:string,fn:()=>Promise<T>):Promise<T>{let p=pending.get(key) as Promise<T>|undefined;if(!p){if(pending.size>=20)throw Error('Gate budget');p=Promise.resolve().then(fn);pending.set(key,p);void p.finally(()=>{if(pending.get(key)===p)pending.delete(key);}).catch(()=>{});}let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([p,new Promise<never>((_r,j)=>{timer=setTimeout(()=>j(Error('Gate timeout')),3000);})]);}finally{clearTimeout(timer);}}
 async function publication(id:string){return bounded('pub:'+id,async()=>{const p=await settings.publication(id);if(p.publication.id!==id||p.publication.status!=='published'||!/^[a-f0-9]{64}$/.test(p.publication.revisionSha256)||!validateExhibition(p.exhibition).valid||!validateStudioPresentation(p.exhibition).valid)throw Error('Unavailable');return p;});}
 const authorized=(subject:OpeningSubject,id:string)=>bounded('host:'+id+':'+subject.sessionId,()=>settings.authorizeHost(subject,id));
 function remove(room:Room,m:Member){m.state.voice=false;m.state.connected=false;room.members.delete(m.state.id);if(m.socket)m.socket.close(1008);}
 function discard(room:Room,code:OpeningErrorCode){if(room.closed)return;room.closed=true;rooms.delete(room.id);for(const c of contexts)if(c.room===room){error(c,code,true);c.member=undefined;c.room=undefined;}room.members.clear();room.messages=[];room.reports=[];}
 async function current(room:Room){if(room.closed)return false;if(Date.now()-room.checkedAt<2000)return true;if(!room.checking)room.checking=(async()=>{try{const p=await publication(room.id);if(room.closed)return false;if(p.publication.revisionSha256!==room.revision){discard(room,'REVISION_CHANGED');return false;}for(const m of room.members.values())if(m.subject&&!await authorized(m.subject,room.id)){m.state.host=false;m.state.voice=false;m.state.muted=true;m.subject=undefined;room.phase='ended';room.guide=null;for(const other of room.members.values())other.state.voice=false;}if(room.closed)return false;room.checkedAt=Date.now();return true;}catch{stats.policyFailures++;discard(room,'PUBLICATION_UNAVAILABLE');return false;}finally{room.checking=undefined;}})();return room.checking;}
 function snapshot(room:Room,m:Member,type:'snapshot'|'welcome',resumeToken?:string){const now=Date.now();room.messages=room.messages.filter(v=>now-v.at<=900000);room.reports=room.reports.filter(v=>now-v.at<=86400000);const common={version:1,type,publicationId:room.id,revisionSha256:room.revision,selfId:m.state.id,serverTime:now,sequence:room.sequence,phase:room.phase,participants:[...room.members.values()].map(v=>({...v.state,voice:v.state.voice&&!m.blocks.has(v.state.id)&&!v.blocks.has(m.state.id)})),guide:room.guide,messages:m.state.chat?room.messages.filter(v=>!m.blocks.has(v.participantId)):[],reports:m.state.host?room.reports:[],blockedIds:[...m.blocks]};return type==='welcome'?{...common,resumeToken,resumeExpiresAt:m.expires}:common;}
 async function join(c:Context,message:Extract<OpeningClientMessage,{type:'join'}>){
  if(c.joined||message.publicationId!==c.pubId){error(c,'PROTOCOL_INVALID',true);return;}c.joined=true;let p:RealtimePublication;try{p=await publication(c.pubId);}catch{error(c,'PUBLICATION_UNAVAILABLE',true);return;}if(!c.alive||c.socket.readyState!==WebSocket.OPEN)return;if(p.publication.revisionSha256!==message.revisionSha256){error(c,'REVISION_CHANGED',true);return;}
  let subject:OpeningSubject|undefined;if(message.hostGrant){const h=hash(message.hostGrant),g=grants.get(h);grants.delete(h);if(!g||g.pubId!==c.pubId||g.expires<Date.now()||!await authorized(g.subject,c.pubId)){error(c,'HOST_GRANT_INVALID',true);return;}subject=g.subject;}if(!c.alive)return;
  let room=rooms.get(c.pubId);if(room&&room.revision!==message.revisionSha256){discard(room,'REVISION_CHANGED');room=undefined;}if(!room){if(rooms.size>=16){error(c,'SERVER_BUSY',true);return;}room={id:c.pubId,revision:message.revisionSha256,members:new Map(),viewpoints:new Set(presentationFor(p.exhibition).viewpoints.map(v=>v.id)),phase:'waiting',guide:null,sequence:0,messages:[],reports:[],checkedAt:Date.now(),closed:false};rooms.set(room.id,room);}else if(!await current(room)||!c.alive)return;
  let m:Member|undefined;if(message.resumeToken){m=[...room.members.values()].find(v=>v.tokenHash===hash(message.resumeToken!));if(!m||m.expires<Date.now()||!m.state.connected&&m.reservedUntil<Date.now()){error(c,'RESUME_INVALID',true);return;}if(m.subject&&!await authorized(m.subject,room.id)){error(c,'HOST_GRANT_INVALID',true);return;}if(!c.alive)return;if(m.socket)m.socket.terminate();m.state.voice=false;}
  else{if(room.members.size>=20){error(c,'ROOM_FULL',true);return;}if(subject&&[...room.members.values()].some(v=>v.state.host)){error(c,'HOST_GRANT_INVALID',true);return;}m={state:{id:randomUUID(),name:'Visitor '+randomBytes(3).toString('hex').toUpperCase(),host:!!subject,chat:false,voice:false,follow:false,muted:false,connected:true},tokenHash:'',expires:Date.now()+ttl,reservedUntil:0,blocks:new Set(),reports:[],subject,chatAt:0,signalTokens:40,signalAt:Date.now()};room.members.set(m.state.id,m);}
  const secret=token();m.tokenHash=hash(secret);m.socket=c.socket;m.state.connected=true;m.reservedUntil=0;c.room=room;c.member=m;clearTimeout(c.timer);stats.joins++;send(c.socket,snapshot(room,m,'welcome',secret));
 }
 async function handle(c:Context,bytes:Buffer,binary:boolean){
  if(!c.alive)return;if(binary||bytes.length>frame){error(c,'PROTOCOL_INVALID',true);return;}let v:unknown;try{v=JSON.parse(bytes.toString('utf8'));}catch{error(c,'PROTOCOL_INVALID',true);return;}if(!validateOpeningClientMessage(v)){error(c,'PROTOCOL_INVALID',true);return;}
  const now=Date.now();c.tokens=Math.min(40,c.tokens+(now-c.at)*20/1000);c.at=now;if(c.tokens<1){error(c,'RATE_LIMITED',true);return;}c.tokens--;
  if(v.type==='join'){await join(c,v);return;}const {room,member:m}=c;if(!room||!m){error(c,'JOIN_REQUIRED',true);return;}if(m.expires<=now){remove(room,m);error(c,'SESSION_EXPIRED',true);return;}if(v.type==='leave'){remove(room,m);c.member=undefined;c.socket.close(1000);return;}
  if(!await current(room)||!c.alive||m.socket!==c.socket||room.closed)return;
  if(v.type==='ping'){send(c.socket,{version:1,type:'pong',seq:v.seq,serverTime:Date.now()});return;}
  if(v.type==='preferences'){if(v.voice&&(m.state.muted||room.phase==='ended')){error(c,room.phase==='ended'?'SESSION_ENDED':'CONSENT_REQUIRED');return;}if(v.voice&&!m.state.voice&&[...room.members.values()].filter(v=>v.state.voice).length>=6){error(c,'VOICE_FULL');return;}Object.assign(m.state,{chat:v.chat,voice:v.voice,follow:v.follow});return;}
  if(v.type==='chat'){if(!m.state.chat){error(c,'CONSENT_REQUIRED');return;}if(room.phase==='ended'){error(c,'SESSION_ENDED');return;}if(now-m.chatAt<1000){error(c,'RATE_LIMITED');return;}m.chatAt=now;room.messages.push({id:randomUUID(),participantId:m.state.id,name:m.state.name,text:v.text,at:now});room.messages=room.messages.slice(-30);stats.chats++;return;}
  if(v.type==='report'){if(!room.members.has(v.targetId)||v.targetId===m.state.id){error(c,'TARGET_UNAVAILABLE');return;}m.reports=m.reports.filter(at=>now-at<86400000);if(m.reports.length>=20){error(c,'RATE_LIMITED');return;}m.reports.push(now);room.reports.push({id:randomUUID(),reporterId:m.state.id,targetId:v.targetId,reason:v.reason,note:v.note,at:now});room.reports=room.reports.slice(-20);stats.reports++;return;}
  if(v.type==='block'){if(v.targetId===m.state.id||!room.members.has(v.targetId)){error(c,'TARGET_UNAVAILABLE');return;}if(!m.blocks.has(v.targetId)&&m.blocks.size>=20){error(c,'RATE_LIMITED');return;}m.blocks.add(v.targetId);return;}
  if(v.type==='signal'){const target=room.members.get(v.targetId);if(!target||target===m||!target.socket||!target.state.connected||target.blocks.has(m.state.id)||m.blocks.has(target.state.id)){error(c,'TARGET_UNAVAILABLE');return;}if(!m.state.voice||!target.state.voice||m.state.muted||target.state.muted||room.phase==='ended'){error(c,'CONSENT_REQUIRED');return;}m.signalTokens=Math.min(40,m.signalTokens+(now-m.signalAt)*10/1000);m.signalAt=now;if(m.signalTokens<1){error(c,'RATE_LIMITED',true);return;}m.signalTokens--;send(target.socket,{version:1,type:'signal',fromId:m.state.id,...(v.description?{description:v.description}:{candidate:v.candidate})});stats.signals++;return;}
  if(v.type==='host'){if(!m.state.host||!m.subject){error(c,'HOST_REQUIRED');return;}switch(v.command){
   case 'begin':room.phase='live';room.guide=null;for(const p of room.members.values()){p.state.muted=false;p.state.voice=false;}break;
   case 'end':room.phase='ended';room.guide=null;for(const p of room.members.values())p.state.voice=false;break;
   case 'guide':case 'meet':if(!room.viewpoints.has(v.viewpointId)){error(c,'VIEWPOINT_INVALID');return;}if(room.phase!=='live'){error(c,'SESSION_ENDED');return;}room.guide={id:v.viewpointId,sequence:room.sequence+1,kind:v.command};break;
   case 'mute_all':for(const p of room.members.values()){p.state.voice=false;p.state.muted=true;}break;
   case 'mute':case 'remove':{const target=room.members.get(v.targetId);if(!target||target===m){error(c,'TARGET_UNAVAILABLE');return;}target.state.voice=false;target.state.muted=true;if(v.command==='remove')remove(room,target);break;}
  }}
 }
 function accept(socket:WebSocket,pubId:string){const c:Context={socket,pubId,alive:true,joined:false,busy:false,queue:[],tokens:40,at:Date.now(),timer:setTimeout(()=>error(c,'JOIN_REQUIRED',true),5000),pongAt:Date.now()};contexts.add(c);socket.on('error',()=>{});socket.on('pong',()=>{c.pongAt=Date.now();});socket.on('close',()=>{c.alive=false;c.queue=[];clearTimeout(c.timer);contexts.delete(c);const {room,member:m}=c;if(room&&m&&m.socket===socket&&!room.closed){m.socket=undefined;m.state.connected=false;m.state.voice=false;m.reservedUntil=Math.min(Date.now()+30000,m.expires);}});socket.on('message',(raw,binary)=>{const bytes=Buffer.isBuffer(raw)?raw:Array.isArray(raw)?Buffer.concat(raw):Buffer.from(raw);if(c.queue.length>=8||bytes.length>frame){error(c,'RATE_LIMITED',true);return;}c.queue.push({bytes,binary});if(c.busy)return;c.busy=true;void(async()=>{while(c.alive&&c.queue.length){const v=c.queue.shift()!;await handle(c,v.bytes,v.binary);}})().catch(()=>{if(c.alive)error(c,'SERVER_BUSY',true);}).finally(()=>{c.busy=false;c.queue=[];});});}
 function upgrade(request:IncomingMessage,socket:Duplex,head:Buffer){const match=/^\/api\/v1\/publications\/([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})\/opening$/.exec(request.url??'');if(!match)return false;const reject=(status:number)=>socket.end(`HTTP/1.1 ${status} Rejected\r\nConnection: close\r\nContent-Length: 0\r\n\r\n`);if(stopping||contexts.size>=200){reject(503);return true;}if(request.headers.origin!==settings.origin||request.headers.host!==origin.host||request.headers['sec-websocket-protocol']){reject(403);return true;}const now=Date.now(),ip=request.socket.remoteAddress??'';for(const [key,v]of ips)if(now-v.at>60000)ips.delete(key);let budget=ips.get(ip);if(!budget){if(ips.size>=256){reject(503);return true;}budget={tokens:60,at:now};ips.set(ip,budget);}budget.tokens=Math.min(60,budget.tokens+(now-budget.at)/1000);budget.at=now;if(budget.tokens<1){reject(429);return true;}budget.tokens--;socket.on('error',()=>{});wss.handleUpgrade(request,socket,head,ws=>accept(ws,match[1]!));return true;}
 const timer=setInterval(()=>{const now=Date.now();for(const [key,g]of grants)if(g.expires<=now)grants.delete(key);for(const room of rooms.values()){for(const m of room.members.values())if(m.expires<=now||!m.state.connected&&m.reservedUntil<=now)remove(room,m);if(!room.members.size){rooms.delete(room.id);continue;}if(now-room.checkedAt>=2000)void current(room);if(room.closed||room.checking)continue;if(room.sequence>=2147483647){discard(room,'SERVER_BUSY');continue;}room.sequence++;for(const m of room.members.values())if(m.socket&&m.state.connected)send(m.socket,snapshot(room,m,'snapshot'));}if(now-lastPing>=5000){lastPing=now;for(const c of contexts){if(now-c.pongAt>15000)c.socket.terminate();else if(c.socket.readyState===WebSocket.OPEN)c.socket.ping();}}},100);timer.unref();
 app.addHook('onClose',async()=>{stopping=true;clearInterval(timer);grants.clear();for(const c of contexts){clearTimeout(c.timer);c.socket.terminate();}contexts.clear();rooms.clear();await new Promise<void>(r=>wss.close(()=>r()));});
 return {upgrade,issueHost:async(pubId:string,subject:OpeningSubject)=>{if(grants.size>=256)throw Error('Host grant budget');await publication(pubId);if(!await authorized(subject,pubId))throw Error('Opening host forbidden');const hostGrant=token(),expiresAt=Date.now()+60000;grants.set(hash(hostGrant),{pubId,subject:{...subject},expires:expiresAt});return {hostGrant,expiresAt};},metrics:()=>({...stats,rooms:rooms.size,connections:contexts.size,participants:[...rooms.values()].reduce((n,r)=>n+r.members.size,0),grants:grants.size})};
}
