// SPDX-License-Identifier: AGPL-3.0-or-later
import { inflateSync,deflateSync } from "node:zlib";
import { validateBytes } from "gltf-validator";
const MAX=33554432;let length=0;const parts:Buffer[]=[];
for await(const chunk of process.stdin){length+=chunk.length;if(length>MAX)process.exit(1);parts.push(chunk);}const input=Buffer.concat(parts);
const fail=():never=>{throw Error("unsupported coarse profile");};
function crc(data:Buffer){let v=0xffffffff;for(const b of data){v^=b;for(let i=0;i<8;i++)v=(v>>>1)^(v&1?0xedb88320:0);}return(v^0xffffffff)>>>0;}
function pngChunk(name:string,body:Buffer){const h=Buffer.alloc(8),tail=Buffer.alloc(4);h.writeUInt32BE(body.length);h.write(name,4);tail.writeUInt32BE(crc(Buffer.concat([h.subarray(4),body])));return Buffer.concat([h,body,tail]);}
function png(data:Buffer){if(data.length<33||!data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))fail();const w=data.readUInt32BE(16),h=data.readUInt32BE(20),channels=data[25]===6?4:data[25]===2?3:0;if(!w||!h||w*h>4194304||w>8192||h>8192||data[24]!==8||!channels||data[28]!==0)fail();const idat:Buffer[]=[];for(let o=8;o<data.length;){const n=data.readUInt32BE(o),end=o+n+12;if(end>data.length)fail();const name=data.toString("ascii",o+4,o+8);if(data.readUInt32BE(end-4)!==crc(data.subarray(o+4,end-4)))fail();if(name==="IDAT")idat.push(data.subarray(o+8,end-4));else if(!["IHDR","IEND"].includes(name))fail();o=end;}
 const pixels=inflateSync(Buffer.concat(idat),{maxOutputLength:(w*channels+1)*h});if(pixels.length!==(w*channels+1)*h)fail();
 const stride=w*channels,row=stride+1,paeth=(a:number,b:number,c:number)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};
 for(let y=0;y<h;y++){const filter=pixels[y*row]!;if(filter>4)fail();for(let x=0;x<stride;x++){const i=y*row+1+x,a=x>=channels?pixels[i-channels]!:0,b=y?pixels[i-row]!:0,c=y&&x>=channels?pixels[i-row-channels]!:0;pixels[i]=(pixels[i]!+(filter===0?0:filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):paeth(a,b,c)))&255;}}
 const ratio=Math.min(1,512/Math.max(w,h)),lw=Math.max(1,Math.round(w*ratio)),lh=Math.max(1,Math.round(h*ratio));
 if(ratio===1)return {full:{textureSize:Math.max(w,h)}};
 const out=Buffer.alloc((lw*channels+1)*lh);for(let y=0;y<lh;y++)for(let x=0;x<lw;x++)for(let c=0;c<channels;c++){let sum=0,count=0;const x0=Math.floor(x*w/lw),x1=Math.max(x0+1,Math.floor((x+1)*w/lw)),y0=Math.floor(y*h/lh),y1=Math.max(y0+1,Math.floor((y+1)*h/lh));for(let sy=y0;sy<y1;sy++)for(let sx=x0;sx<x1;sx++){sum+=pixels[sy*row+1+sx*channels+c]!;count++;}out[y*(lw*channels+1)+1+x*channels+c]=Math.round(sum/count);}
 const ihdr=Buffer.from(data.subarray(16,29));ihdr.writeUInt32BE(lw,0);ihdr.writeUInt32BE(lh,4);const bytes=Buffer.concat([data.subarray(0,8),pngChunk("IHDR",ihdr),pngChunk("IDAT",deflateSync(out)),pngChunk("IEND",Buffer.alloc(0))]);return {full:{textureSize:Math.max(w,h)},...(bytes.length<data.length?{coarse:{textureSize:Math.max(lw,lh)},bytes}:{})};
}
async function glb(data:Buffer){const validation=await validateBytes(data,{maxIssues:32,externalResourceFunction:()=>Promise.reject(Error("external resource rejected"))});if(validation.issues.numErrors||data.length<28||data.readUInt32LE(8)!==data.length)fail();const size=data.readUInt32LE(12);if(size>1048576)fail();const source=JSON.parse(data.toString("utf8",20,20+size)),bin=data.subarray(28+size);if(source.animations?.length||source.skins?.length||source.extensionsUsed?.length||source.textures?.length||source.images?.length||source.buffers?.length!==1||source.buffers[0].uri)fail();
 const identity=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];for(const n of source.nodes??[])if((n.matrix&&JSON.stringify(n.matrix)!==JSON.stringify(identity))||(n.translation&&n.translation.some((v:number)=>v!==0))||(n.rotation&&JSON.stringify(n.rotation)!=="[0,0,0,1]")||(n.scale&&n.scale.some((v:number)=>v!==1)))fail();
 const buffers:Buffer[]=[],views:Record<string,unknown>[]=[],accessors:Record<string,unknown>[]=[];let offset=0,fullTriangles=0,coarseTriangles=0,vertices=0;
 const read=(index:number,type:string)=>{const a=source.accessors[index],v=source.bufferViews[a?.bufferView];if(!a||!v||a.sparse||a.type!==type||v.buffer!==0||(type==="VEC3"&&a.componentType!==5126)||(type==="SCALAR"&&![5121,5123,5125].includes(a.componentType)))fail();const count=a.count,components=type==="VEC3"?3:1,width=a.componentType===5126||a.componentType===5125?4:a.componentType===5123?2:a.componentType===5121?1:0;if(!Number.isInteger(v.byteLength)||v.byteLength<1||(v.byteOffset??0)+v.byteLength>bin.length||!width||!Number.isInteger(count)||count<1||count>200000)fail();const values:number[]=[];for(let i=0;i<count;i++)for(let c=0;c<components;c++){const pos=(v.byteOffset??0)+(a.byteOffset??0)+i*(v.byteStride??components*width)+c*width;if(pos<(v.byteOffset??0)||pos+width>(v.byteOffset??0)+v.byteLength||pos+width>bin.length)fail();const val=a.componentType===5126?bin.readFloatLE(pos):width===4?bin.readUInt32LE(pos):width===2?bin.readUInt16LE(pos):bin[pos]!;if(!Number.isFinite(val))fail();values.push(val);}return values;};
 const append=(values:number[],type:"VEC3"|"SCALAR",target:number,min?:number[],max?:number[])=>{const b=Buffer.alloc(values.length*4);values.forEach((v,i)=>type==="VEC3"?b.writeFloatLE(v,i*4):b.writeUInt32LE(v,i*4));const vi=views.length;views.push({buffer:0,byteOffset:offset,byteLength:b.length,target});buffers.push(b);offset+=b.length;const ai=accessors.length;accessors.push({bufferView:vi,componentType:type==="VEC3"?5126:5125,count:values.length/(type==="VEC3"?3:1),type,...(min?{min,max}:{})});return ai;};
 const meshes=[];
 for(const [mi,m] of (source.meshes??[]).entries()){const instances=(source.nodes??[]).filter((n:{mesh?:number})=>n.mesh===mi).length;if(!instances)fail();const primitives=[];for(const p of m.primitives??[]){if((p.mode??4)!==4||p.targets||Object.keys(p.attributes).some(k=>!["POSITION","NORMAL"].includes(k)))fail();const original=read(p.attributes.POSITION,"VEC3"),indices=p.indices===undefined?Array.from({length:original.length/3},(_,i)=>i):read(p.indices,"SCALAR");if(indices.length%3||indices.some(i=>!Number.isSafeInteger(i)||i<0||i>=original.length/3))fail();vertices+=original.length/3;if(vertices>100000||fullTriangles+indices.length/3>200000)fail();fullTriangles+=indices.length/3*instances;
 const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<original.length;i++){const axis=i%3;min[axis]=Math.min(min[axis]!,original[i]!);max[axis]=Math.max(max[axis]!,original[i]!);}
 const positions:number[]=[],mapping:number[]=[],clusters=new Map<string,number>();for(let i=0;i<original.length;i+=3){const point=[0,1,2].map(a=>{const span=max[a]!-min[a]!;return span===0?min[a]!:min[a]!+Math.round((original[i+a]!-min[a]!)/span*16)/16*span;});const key=point.join(",");if(!clusters.has(key)){clusters.set(key,positions.length/3);positions.push(...point);}mapping.push(clusters.get(key)!);}
 const low:number[]=[],seen=new Set<string>();for(let i=0;i<indices.length;i+=3){const a=mapping[indices[i]!]!,b=mapping[indices[i+1]!]!,c=mapping[indices[i+2]!]!;if(a===b||b===c||a===c)continue;const key=[a,b,c].sort((a,b)=>a-b).join(",");if(seen.has(key))continue;const ab=[0,1,2].map(n=>positions[b*3+n]!-positions[a*3+n]!),ac=[0,1,2].map(n=>positions[c*3+n]!-positions[a*3+n]!);if(Math.hypot(ab[1]!*ac[2]!-ab[2]!*ac[1]!,ab[2]!*ac[0]!-ab[0]!*ac[2]!,ab[0]!*ac[1]!-ab[1]!*ac[0]!)<1e-12)continue;seen.add(key);low.push(a,b,c);}
 if(!low.length)fail();coarseTriangles+=low.length/3*instances;const normals=Array(positions.length).fill(0) as number[];for(let i=0;i<low.length;i+=3){const [a,b,c]=low.slice(i,i+3),ab=[0,1,2].map(n=>positions[b!*3+n]!-positions[a!*3+n]!),ac=[0,1,2].map(n=>positions[c!*3+n]!-positions[a!*3+n]!),normal=[ab[1]!*ac[2]!-ab[2]!*ac[1]!,ab[2]!*ac[0]!-ab[0]!*ac[2]!,ab[0]!*ac[1]!-ab[1]!*ac[0]!];for(const v of [a!,b!,c!])for(let n=0;n<3;n++)normals[v*3+n]!+=normal[n]!;}
 for(let i=0;i<normals.length;i+=3){const norm=Math.hypot(...normals.slice(i,i+3));for(let n=0;n<3;n++)normals[i+n]=norm?normals[i+n]!/norm:n===1?1:0;}
 primitives.push({attributes:{POSITION:append(positions,"VEC3",34962,min,max),NORMAL:append(normals,"VEC3",34962)},indices:append(low,"SCALAR",34963),mode:4,...(p.material===undefined?{}:{material:p.material})});}meshes.push({primitives});}
 if(coarseTriangles>=fullTriangles)return {full:{triangles:fullTriangles}};
 const doc={asset:{version:"2.0",generator:"ExhibitOS deterministic vertex clustering v1"},scene:0,scenes:source.scenes,nodes:source.nodes,meshes,materials:source.materials,bufferViews:views,accessors,buffers:[{byteLength:offset}]};const json=Buffer.from(JSON.stringify(doc)),padded=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]),h=Buffer.alloc(20),bh=Buffer.alloc(8),body=Buffer.concat(buffers);h.write("glTF");h.writeUInt32LE(2,4);h.writeUInt32LE(28+padded.length+body.length,8);h.writeUInt32LE(padded.length,12);h.writeUInt32LE(0x4e4f534a,16);bh.writeUInt32LE(body.length);bh.writeUInt32LE(0x004e4942,4);const bytes=Buffer.concat([h,padded,bh,body]);const report=await validateBytes(bytes,{maxIssues:32,externalResourceFunction:()=>Promise.reject(Error("external rejected"))});if(report.issues.numErrors)fail();return {full:{triangles:fullTriangles},...(bytes.length<data.length?{coarse:{triangles:coarseTriangles},bytes}:{})};
}
try{const result=process.argv[2]==="image/png"?png(input):await glb(input);const {bytes,...metadata}=result;const json=Buffer.from(JSON.stringify(metadata)),header=Buffer.alloc(8);header.write("ELOD");header.writeUInt32LE(json.length,4);process.stdout.write(Buffer.concat([header,json,bytes??Buffer.alloc(0)]));}catch{process.exitCode=1;}
