// SPDX-License-Identifier: AGPL-3.0-or-later
import { chromium, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { mkdtemp,writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
export async function runCurationBrowser({origin,authoring}) {
 const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage(),checks=[],observations=[],errors=[];
 const dir=await mkdtemp(`${tmpdir()}/exhibitos-curation-browser-`),screenshots=[];
 page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
 const button=name=>page.getByRole('button',{name,exact:true});
 const edit=page.getByRole('region',{name:'공간 오디오와 안내 동선 편집',exact:true});
 const old=page.getByRole('region',{name:'관람 오디오와 작품 설명 편집',exact:true});
 const stored=()=>page.getByLabel('전시 문서 JSON',{exact:true}).inputValue().then(JSON.parse);
 const record=async()=>{const id=await page.getByTestId('draft-id').innerText();return page.evaluate(id=>new Promise((resolve,reject)=>{const open=indexedDB.open('exhibitos-studio',2);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,get=db.transaction('drafts').objectStore('drafts').get(id);get.onsuccess=()=>{db.close();resolve(get.result);};get.onerror=()=>{db.close();reject(get.error);};};}),id);};
 const saved=async()=>{const expected=await stored();await expect.poll(async()=>JSON.stringify((await record()).draft.candidate)).toBe(JSON.stringify(expected));await expect(page.getByTestId('local-state')).toContainText('로컬 version');};
 const check=async(title,fn)=>{await fn();checks.push(title);console.log(`PASS ${title}`);};
 const remoteSave=async()=>{await page.getByRole('button',{name:/^(기록된 ETag로 서버 저장|현재 계정에 새 서버 전시 저장)$/}).click();await expect(page.getByRole('status',{name:'전시 편집 상태',exact:true})).toContainText('서버 revision');await saved();};
 try {
  await page.goto(`${origin}/cms`);await page.getByLabel('기관 ID',{exact:true}).fill(authoring.tenantId);await page.getByLabel('계정',{exact:true}).fill(authoring.subject);await page.getByLabel('비밀번호',{exact:true}).fill(authoring.password);await button('로그인').click();await expect(button('로그아웃')).toBeVisible();
  await page.goto(`${origin}/studio`);await button('새 로컬 전시').click();await expect(page.getByRole('status',{name:'전시 편집 상태',exact:true})).toContainText('만들었습니다');
  const local=await stored(),candidate=structuredClone(authoring.candidate);candidate.id=local.id;candidate.revisionId=randomUUID();candidate.mediaAssets=[];candidate.audioZones=[];candidate.navigation=[];candidate.accessibility.routeIds=[];delete candidate.extensions['org.exhibitos.viewer/curation'];candidate.extensions['org.exhibitos.viewer/experience'].voices=[];
  await page.getByLabel('전시 문서 JSON',{exact:true}).fill(JSON.stringify(candidate));await saved();await button('현재 서버 계정 확인').click();await remoteSave();
  await old.getByLabel('작가 음성 WAV 파일',{exact:true}).setInputFiles({name:'original-curation-tone.wav',mimeType:'audio/wav',buffer:authoring.wave});
  await old.getByLabel('오디오 권리자',{exact:true}).fill('Synthetic curation author');await old.getByLabel('오디오 크레딧',{exact:true}).fill('Original synthetic curation tone');await old.getByLabel('오디오 라이선스 식별자',{exact:true}).fill('CC0-1.0');await old.getByLabel('이 녹음의 권리자로서 공개 재생을 허용합니다',{exact:true}).check();
  await button('오디오 업로드·검증').click();await expect(button('오디오 승인')).toBeVisible();await button('오디오 승인').click();
  await old.getByLabel('설명할 작품 배치',{exact:true}).selectOption(candidate.placements[0].id);await old.getByLabel('승인된 오디오',{exact:true}).selectOption({index:1});await old.getByLabel('음성 대본',{exact:true}).fill('Curation original complete author transcript');await button('작품 음성 연결').click();await saved();await button('작품 위치에 공간 오디오 추가').click();await saved();
  await check('actual Studio zone attenuation, timed originals/translations and annotation translations preserve source then reload IndexedDB',async()=>{
   await edit.getByLabel('편집할 오디오 구역',{exact:true}).selectOption({index:1});await edit.getByLabel('최대 청취 거리 (m)',{exact:true}).fill('10');await edit.getByLabel('차폐된 소리 비율',{exact:true}).fill('.25');await button('오디오 거리·차폐 적용').click();await saved();
   await edit.getByLabel('시간 대본 음성',{exact:true}).selectOption({index:1});await edit.getByLabel('음성 전체 길이 (초)',{exact:true}).fill('2');await edit.getByLabel('대본 시작 (초)',{exact:true}).fill('0');await edit.getByLabel('대본 끝 (초)',{exact:true}).fill('1');await edit.getByLabel('시간 대본 글',{exact:true}).fill('Original first cue');await button('원문 시간 대본 추가·갱신').click();await saved();
   await edit.getByLabel('대본 시작 (초)',{exact:true}).fill('1');await edit.getByLabel('대본 끝 (초)',{exact:true}).fill('2');await edit.getByLabel('시간 대본 글',{exact:true}).fill('Original second cue');await button('원문 시간 대본 추가·갱신').click();await saved();
   const originalCues=(await stored()).extensions['org.exhibitos.viewer/curation'].transcripts[0].cues;
   await edit.getByLabel('대본 시작 (초)',{exact:true}).fill('0');await edit.getByLabel('대본 끝 (초)',{exact:true}).fill('2');await edit.getByLabel('시간 대본 글',{exact:true}).fill('Separate translated complete cue');await button('번역 시간 대본 추가·갱신').click();await saved();
   const before=await stored();assert.deepEqual(before.extensions['org.exhibitos.viewer/curation'].transcripts[0].cues,originalCues);assert.equal(before.extensions['org.exhibitos.viewer/experience'].voices[0].transcript,'Curation original complete author transcript');
   await edit.getByLabel('편집할 위치 주석',{exact:true}).selectOption(candidate.annotations[0].id);await edit.getByLabel('주석 번역문',{exact:true}).fill('Separate translated anchored note');await button('주석 번역 적용').click();await saved();
   const final=await stored(),id=await page.getByTestId('draft-id').innerText();await page.reload();await page.getByTestId(`draft-${id}`).click();await saved();assert.deepEqual(await stored(),final);
   await edit.getByLabel('시간 대본 음성',{exact:true}).selectOption({index:1});await edit.getByLabel('대본 시작 (초)',{exact:true}).fill('-1');await edit.getByLabel('시간 대본 글',{exact:true}).fill('invalid must not replace');await button('원문 시간 대본 추가·갱신').click();assert.deepEqual(await stored(),final);await expect(edit.getByRole('status')).toContainText('이전 문서는 유지됩니다');
  });
  await check('actual guided route authoring preserves cross-room door references, edits stops and persists protected server revision',async()=>{
   await edit.getByLabel('안내 동선 이름',{exact:true}).fill('Authored accessible curation route');await edit.getByLabel('안내 정류점 공간',{exact:true}).selectOption(candidate.rooms[0].id);await edit.getByLabel('정류점 좌표 Z',{exact:true}).fill('3');await edit.getByLabel('정류점 제목',{exact:true}).fill('Original entrance stop');await edit.getByLabel('정류점 글 설명',{exact:true}).fill('Read the complete entrance content without walking or sound.');await button('안내 정류점 추가·갱신').click();await saved();
   const door=candidate.openings.find(o=>o.type==='door'&&candidate.surfaces.find(s=>s.id===o.surfaceId)?.roomId===candidate.rooms[0].id);
   await edit.getByLabel('안내 정류점 공간',{exact:true}).selectOption(candidate.rooms[1].id);await edit.getByLabel('정류점 좌표 Z',{exact:true}).fill('0');await edit.getByLabel('정류점 연결 문',{exact:true}).selectOption(door.id);await edit.getByLabel('정류점 제목',{exact:true}).fill('Original adjacent stop');await edit.getByLabel('정류점 글 설명',{exact:true}).fill('The next room content remains available in stationary reading.');await button('안내 정류점 추가·갱신').click();await saved();
   await button('안내 정류점 선택 2').click();await edit.getByLabel('정류점 글 설명',{exact:true}).fill('Edited adjacent content, source language retained.');await button('안내 정류점 추가·갱신').click();await saved();assert.equal((await stored()).navigation[0].waypoints[1].viaOpeningId,door.id);
   await button('현재 서버 계정 확인').click();await remoteSave();
  });
  await check('authenticated malformed cross-profile input fails closed as422 without replacing the saved revision',async()=>{
   const session=await (await context.request.get(`${origin}/api/v1/auth/session`)).json(),r=await record(),bad=structuredClone(r.draft);bad.candidate.extensions['org.exhibitos.viewer/experience'].voices=[null];
   const response=await context.request.put(`${origin}/api/v1/tenants/${authoring.tenantId}/studio/exhibitions/${r.remote.id}`,{headers:{origin,'x-csrf-token':session.csrfToken,'if-match':r.remote.etag},data:{requestId:randomUUID(),draft:bad}});assert.equal(response.status(),422);assert.equal((await response.json()).code,'DRAFT_INVALID');
   const current=await context.request.get(`${origin}/api/v1/tenants/${authoring.tenantId}/studio/exhibitions/${r.remote.id}`);assert.equal(current.status(),200);assert.equal(current.headers().etag,r.remote.etag);
  });
  await check('actual server READY and direct publication reject a declared cue duration inconsistent with approved PCM',async()=>{
   await edit.getByLabel('시간 대본 음성',{exact:true}).selectOption({index:1});await button('원문 시간 대본 선택 1').click();await edit.getByLabel('음성 전체 길이 (초)',{exact:true}).fill('3');await button('원문 시간 대본 추가·갱신').click();await saved();await remoteSave();await button('서버 revision READY 검사').click();await expect(page.getByTestId('ready-state')).toHaveText('BLOCKED');await expect(page.getByRole('region',{name:'READY 검사 결과',exact:true})).toContainText('CURATION_AUDIO_DURATION');
   const session=await (await context.request.get(`${origin}/api/v1/auth/session`)).json(),r=await record();const rejected=await context.request.post(`${origin}/api/v1/tenants/${authoring.tenantId}/studio/exhibitions/${r.remote.id}/publications`,{headers:{origin,'x-csrf-token':session.csrfToken,'if-match':r.remote.etag},data:{requestId:randomUUID()}});assert.equal(rejected.status(),422);assert.equal((await rejected.json()).code,'PUBLICATION_NOT_READY');
   await button('원문 시간 대본 선택 1').click();await edit.getByLabel('음성 전체 길이 (초)',{exact:true}).fill('2');await button('원문 시간 대본 추가·갱신').click();await saved();assert.equal((await stored()).extensions['org.exhibitos.viewer/curation'].transcripts[0].durationSeconds,2);await remoteSave();
  });
  await button('서버 revision READY 검사').click();await expect(page.getByTestId('ready-state')).toContainText('READY');await button('READY revision 공개').click();await expect(page.getByTestId('publication-status')).toContainText('공개');
  const href=await page.getByRole('link',{name:'익명 공개 preview 열기',exact:true}).getAttribute('href');assert(href);
  const anon=await browser.newContext(),viewer=await anon.newPage();viewer.setDefaultTimeout(30000);viewer.on('pageerror',e=>errors.push(e.message));let wavRequests=0;viewer.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/v1/publications/')&&new URL(r.url()).pathname.includes('/assets/'))wavRequests++;});
  const click=name=>viewer.getByRole('button',{name,exact:true}).click();const sound=()=>viewer.getByTestId('audio-state').evaluate(e=>JSON.parse(e.dataset.audioState));
  await viewer.goto(`${origin}${href}`);
  await check('published authored route is keyboard-readable in default text mode with no asset or audio request and returns focus',async()=>{
   const opener=viewer.getByRole('button',{name:'안내 시작 Authored accessible curation route',exact:true});await opener.focus();await viewer.keyboard.press('Enter');await expect(viewer.getByRole('heading',{name:/Authored accessible curation route · 정류점 1/})).toBeFocused();await expect(viewer.getByRole('group',{name:'선택한 안내 정류점',exact:true}).getByText('Read the complete entrance content without walking or sound.',{exact:true})).toBeVisible();await click('안내 다음 정류점');await expect(viewer.getByRole('group',{name:'선택한 안내 정류점',exact:true}).getByText('Edited adjacent content, source language retained.',{exact:true})).toBeVisible();await click('안내 종료');await expect(opener).toBeFocused();assert.equal(wavRequests,0);
  });
  await click('3D 관람 시작');await expect(viewer.getByTestId('audio-state')).toBeVisible();
  const projection=await (await anon.request.get(`${origin}/api/v1/publications/${href.split('/').at(-1)}`)).json(),voice=projection.exhibition.extensions['org.exhibitos.viewer/experience'].voices[0],art=projection.exhibition.artworks.find(a=>a.revisionId===projection.exhibition.placements[0].artworkRevisionId);
  await check('actual WebAudio clock activates original timed cues, separates translations, then stop clears highlight without losing text',async()=>{
   await viewer.getByRole('button',{name:`${art.metadata.title} 상세 보기`,exact:true}).click();const dialog=viewer.getByRole('dialog');await expect(dialog.getByText('Curation original complete author transcript',{exact:false})).toBeVisible();await expect(dialog.getByText('Separate translated anchored note',{exact:false})).toBeVisible();
   await dialog.getByRole('button',{name:'작가 음성 듣기 (ko)',exact:true}).click();await expect.poll(async()=>(await sound()).voice.status).toBe('playing');await expect(dialog.getByTestId('current-transcript-cue')).toHaveText('Original first cue');await expect.poll(async()=>(await sound()).voice.positionSeconds).toBeGreaterThan(.1);await expect(dialog.getByTestId('current-transcript-cue')).toHaveText('Original second cue');
   await dialog.getByRole('button',{name:'음성 정지',exact:true}).click();await expect(dialog.getByTestId('current-transcript-cue')).toHaveText('현재 재생 구간 없음');await expect(dialog.getByText('Separate translated complete cue',{exact:false})).toBeVisible();await dialog.getByRole('button',{name:'상세 보기 닫기',exact:true}).click();assert.equal((await sound()).voice.assetId,voice.assetId);
  });
  await check('actual opt-in walking enters and leaves a zone with bounded gain/reverb; mute stops sources and explicit guide changes only stationary camera',async()=>{
   await viewer.getByLabel('구역에 들어갈 때 소리 재생 (선택)',{exact:true}).check();await click('걷기 시작');const canvas=viewer.getByRole('region',{name:'전시 Viewer',exact:true}).locator('.geometry-preview canvas');const nav=()=>canvas.evaluate(c=>JSON.parse(c.dataset.navigationState ?? "null"));await expect.poll(async()=>(await nav())?.paused).toBe(false);await canvas.focus();await viewer.keyboard.down('ArrowUp');
   try {await expect.poll(async()=>(await sound()).zoneId,{timeout:12000}).not.toBe(null);const inside=await sound();assert(inside.zoneGain>=0&&inside.zoneGain<=1);assert(inside.reverbSeconds>=.15&&inside.reverbSeconds<=1.8);await expect.poll(async()=>(await nav()).eyePosition[2],{timeout:12000}).toBeLessThan(-2);await expect.poll(async()=>(await sound()).zoneId).toBe(null);}finally{await viewer.keyboard.up('ArrowUp');await viewer.keyboard.press('Escape');}
   await viewer.getByLabel('소리 끄기',{exact:true}).check();await expect.poll(async()=>(await sound()).active).toBe(0);const before=await sound();await click('안내 시작 Authored accessible curation route');await click('안내 다음 정류점');assert.equal((await sound()).roomId,before.roomId);await click('선택 정류점의 3D 정지 시점 보기');await expect.poll(async()=>(await sound()).roomId).toBe(projection.exhibition.rooms[1].id);assert.equal((await nav()).paused,true);assert.equal(await viewer.evaluate(()=>document.pointerLockElement===null),true);assert.equal((await sound()).active,0);await click('안내 종료');
  });
  await check('actual missing WAV request rejects playback but original and translated timed text remain readable',async()=>{
   const missing=await browser.newContext(),p=await missing.newPage();await p.route(`${origin}/api/v1/publications/${href.split('/').at(-1)}/assets/${voice.assetId}`,r=>r.abort('failed'));await p.goto(`${origin}${href}`);await p.getByRole('button',{name:'3D 관람 시작',exact:true}).click();await expect(p.getByTestId('audio-state')).toBeVisible();await p.getByRole('button',{name:`${art.metadata.title} 상세 보기`,exact:true}).click();const d=p.getByRole('dialog');await d.getByRole('button',{name:'작가 음성 듣기 (ko)',exact:true}).click();await expect(d.getByRole('status').filter({hasText:'음성을 재생할 수 없습니다. 대본을 읽어주세요.'})).toBeVisible();await expect(d.getByTestId('current-transcript-cue')).toHaveText('현재 재생 구간 없음');await expect(d.getByText('Separate translated complete cue',{exact:false})).toBeVisible();await expect(d.getByText('Curation original complete author transcript',{exact:false})).toBeVisible();await missing.close();
  });
  const shot=`${dir}/curation-public.png`;await viewer.screenshot({path:shot,fullPage:true});screenshots.push(shot);await anon.close();assert.deepEqual(errors,[]);
  observations.push({sourceTranscriptPreserved:true,realClock:true,defaultTextAssetRequests:0,routeDoorReferencePreserved:true});const report={checks,observations,screenshots,scope:'Actual production Chromium editor, protected server save/publication, public timed WebAudio and stationary keyboard route; synthetic PCM only, not physical audibility'};await writeFile(`${dir}/curation-run.json`,JSON.stringify(report,null,2));return report;
 } catch(error){await page.screenshot({path:`${dir}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${dir}/failure.html`,await page.content());await writeFile(`${dir}/failure.json`,JSON.stringify({checks,error:String(error),errors,visibleStatus:await page.getByRole('status').allTextContents().catch(()=>[])},null,2));console.error(`CURATION FAILURE ${dir}`);throw error;}finally{await browser.close();}
}
