// SPDX-License-Identifier: AGPL-3.0-or-later
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fixtureURL} from '@exhibitos/spec';
import {decode} from '../apps/api/dist/imports.js';
import {derivative} from '../apps/api/dist/derivative.js';
import {viewerVariants,measureFullVariant} from '../apps/api/dist/viewer-variants.js';
import {publicTexturedGLB,publicTexturePNG,changeTextureGLB,texturePNGChunk} from './embedded-texture-fixture.mjs';
const mime='model/gltf-binary',parse=b=>JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));
test('public independent embedded PNG plane is accepted by isolated profile and official validator',async()=>{await decode(publicTexturedGLB(),mime);await decode(await readFile(fixtureURL('fixtures/synthetic/sculpture.glb')),mime);});
test('watermark clone retains exact image views and full source while unsupported coarse texture falls back explicitly',async()=>{const source=publicTexturedGLB(),marked=await derivative(source,mime),a=parse(source),b=parse(marked),bin=buf=>buf.subarray(28+buf.readUInt32LE(12));await decode(marked,mime);assert.deepEqual(b.images,a.images);for(const image of a.images){const v=a.bufferViews[image.bufferView];assert.deepEqual(bin(marked).subarray(v.byteOffset,v.byteOffset+v.byteLength),bin(source).subarray(v.byteOffset,v.byteOffset+v.byteLength));}const full=measureFullVariant(marked,mime);assert.equal(full.textureSize,2);await assert.rejects(viewerVariants(marked,mime),/COARSE_UNAVAILABLE/);assert.deepEqual(measureFullVariant(marked,mime),full);});
test('external buffers images extensions and unsupported image/sampler/material references are refused',async()=>{for(const edit of [d=>d.buffers[0].uri='https://example.invalid/a.bin',d=>d.images[0].uri='https://example.invalid/a.png',d=>d.images[0].mimeType='image/jpeg',d=>d.extensions={unknown:{}},d=>d.asset.extras={nested:{uri:'file:///private'}},d=>d.samplers[0].minFilter=9987,d=>d.samplers[0].wrapS=10497,d=>d.samplers[0].unknown=true,d=>d.textures[0].source=8,d=>d.materials[0].normalTexture={index:0},d=>d.materials[0].pbrMetallicRoughness.baseColorTexture.texCoord=1,d=>d.materials[0].pbrMetallicRoughness.baseColorTexture.index=8])await assert.rejects(decode(changeTextureGLB(publicTexturedGLB(),edit),mime));});
test('image CRC truncated streams inflate bomb and overlarge/aggregate dimensions are refused before unbounded expansion',async()=>{const valid=publicTexturePNG(),crc=Buffer.from(valid);crc[29]^=1;await assert.rejects(decode(publicTexturedGLB({png:crc}),mime));await assert.rejects(decode(publicTexturedGLB({png:valid.subarray(0,valid.length-3)}),mime));await assert.rejects(decode(publicTexturedGLB({png:publicTexturePNG(2050,2)}),mime));const body=Buffer.from(publicTexturePNG(1024,1024));await assert.rejects(decode(publicTexturedGLB({png:body,images:3}),mime));const h=Buffer.alloc(13);h.writeUInt32BE(2);h.writeUInt32BE(2,4);h[8]=8;h[9]=6;const expanded=publicTexturePNG(64,64),idat=expanded.subarray(33,expanded.length-12);const bomb=Buffer.concat([valid.subarray(0,8),texturePNGChunk('IHDR',h),idat,texturePNGChunk('IEND',Buffer.alloc(0))]);await assert.rejects(decode(publicTexturedGLB({png:bomb}),mime));});
test('exact chunk image-view boundaries finite UV and declaration mismatches fail closed',async()=>{for(const edit of [d=>d.bufferViews[d.images[0].bufferView].byteLength=0,d=>d.bufferViews[d.images[0].bufferView].byteOffset=999999,d=>d.buffers[0].byteLength=1,d=>d.accessors[2].count=5,(_d,b)=>b.writeFloatLE(NaN,96),(_d,b)=>b.writeFloatLE(1.1,96)])await assert.rejects(decode(changeTextureGLB(publicTexturedGLB(),edit),mime));const trailing=Buffer.concat([publicTexturedGLB(),Buffer.alloc(4)]);trailing.writeUInt32LE(trailing.length,8);await assert.rejects(decode(trailing,mime));});
