// SPDX-License-Identifier: AGPL-3.0-or-later
import {chromium,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import assert from 'node:assert/strict';
const NS='org.exhibitos.runtime/spatial-scripting';
export async function runScriptingBrowser({origin,authoring}) {
 const browser=await chromium.launch({headless:true}),context=await browser.newContext(),page=await context.newPage(),checks=[],errors=[];
 const dir=await mkdtemp(`${tmpdir()}/exhibitos-scripting-browser-`);
 page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
 const button=name=>page.getByRole('button',{name,exact:true}),stored=()=>page.getByLabel('전시 문서 JSON',{exact:true}).inputValue().then(JSON.parse);
 const record=async()=>{const id=await page.getByTestId('draft-id').innerText();return page.evaluate(id=>new Promise((resolve,reject)=>{const open=indexedDB.open('exhibitos-studio',2);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,get=db.transaction('drafts').objectStore('drafts').get(id);get.onsuccess=()=>{db.close();resolve(get.result);};get.onerror=()=>{db.close();reject(get.error);};};}),id);};
 const saved=async()=>{const expected=await stored();await expect.poll(async()=>JSON.stringify((await record()).draft.candidate)).toBe(JSON.stringify(expected));};
 const check=async(title,fn)=>{await fn();checks.push(title);console.log(`PASS ${title}`);};
 try {
  await page.goto(`${origin}/cms`);await page.getByLabel('기관 ID',{exact:true}).fill(authoring.tenantId);await page.getByLabel('계정',{exact:true}).fill(authoring.subject);await page.getByLabel('비밀번호',{exact:true}).fill(authoring.password);await button('로그인').click();await expect(button('로그아웃')).toBeVisible();
  await page.goto(`${origin}/studio`);await button('새 로컬 전시').click();await expect(page.getByRole('status',{name:'전시 편집 상태',exact:true})).toContainText('만들었습니다');
  const local=await stored(),candidate=structuredClone(authoring.candidate);candidate.id=local.id;candidate.revisionId=randomUUID();candidate.mediaAssets=[];candidate.audioZones=[];candidate.navigation=[];candidate.accessibility.routeIds=[];delete candidate.extensions['org.exhibitos.viewer/curation'];delete candidate.extensions[NS];candidate.extensions['org.exhibitos.viewer/experience'].voices=[];
  await page.getByLabel('전시 문서 JSON',{exact:true}).fill(JSON.stringify(candidate));await saved();await button('point 조명 추가').click();await saved();candidate.lights=(await stored()).lights;
  const edit=page.getByRole('region',{name:'Spatial Scripting 편집기',exact:true});
  const b=name=>edit.getByRole('button',{name,exact:true}),label=name=>edit.getByLabel(name,{exact:true});
  await check('production block editor applies ordered text/light/visibility actions and preserves invalid edits and IndexedDB reload',async()=>{
   await b('규칙 추가').click();await label('규칙 ID').fill('authored-start');await label('안내 텍스트 1').fill('Script source text '+candidate.rooms[0].id);
   await label('추가할 동작').selectOption('set_light');await b('동작 추가').click();await label('조명 배율 2').fill('0.4');await label('AFTER 밀리초 2').fill('800');
   await label('추가할 동작').selectOption('set_artwork_visibility');await b('동작 추가').click();await label('작품 표시 3').uncheck();await label('AFTER 밀리초 3').fill('800');await b('규칙 적용').click();await saved();
   const applied=await stored();assert.equal(applied.extensions[NS].rules[0].id,'authored-start');assert.equal(applied.extensions[NS].rules[0].actions.length,3);
   await label('AFTER 밀리초 2').fill('-1');await b('규칙 적용').click();assert.deepEqual(await stored(),applied);await expect(edit.getByRole('status')).toContainText('원본 문서와 입력을 유지');await b('규칙 다시 불러오기').click();
   await b('시뮬레이션 이벤트 전달').click();let simulation=JSON.parse(await page.getByTestId('spatial-simulation').innerText());assert.equal(simulation.actions[0].type,'show_text');assert.equal(simulation.state.pending,2);
   await label('시뮬레이션 시계 경과 밀리초').fill('1600');await b('시뮬레이션 시계 진행').click();simulation=JSON.parse(await page.getByTestId('spatial-simulation').innerText());assert.deepEqual(simulation.actions.map(a=>a.type),['set_light','set_artwork_visibility']);await b('시뮬레이션 취소').click();
   const id=await page.getByTestId('draft-id').innerText();await page.reload();await page.getByTestId(`draft-${id}`).click();await saved();assert.deepEqual(await stored(),applied);
  });
  await button('현재 서버 계정 확인').click();await page.getByRole('button',{name:/^(기록된 ETag로 서버 저장|현재 계정에 새 서버 전시 저장)$/}).click();await expect(page.getByRole('status',{name:'전시 편집 상태',exact:true})).toContainText('서버 revision');await saved();
  const old=page.getByRole('region',{name:'관람 오디오와 작품 설명 편집',exact:true});
  await old.getByLabel('작가 음성 WAV 파일',{exact:true}).setInputFiles({name:'script-tone.wav',mimeType:'audio/wav',buffer:authoring.wave});await old.getByLabel('오디오 권리자',{exact:true}).fill('Synthetic script author');await old.getByLabel('오디오 크레딧',{exact:true}).fill('Original synthetic script tone');await old.getByLabel('오디오 라이선스 식별자',{exact:true}).fill('CC0-1.0');await old.getByLabel('이 녹음의 권리자로서 공개 재생을 허용합니다',{exact:true}).check();await button('오디오 업로드·검증').click();await expect(button('오디오 승인')).toBeVisible();await button('오디오 승인').click();
  await old.getByLabel('설명할 작품 배치',{exact:true}).selectOption(candidate.placements[0].id);await old.getByLabel('승인된 오디오',{exact:true}).selectOption({index:1});await old.getByLabel('음성 대본',{exact:true}).fill('Readable original script audio');await button('작품 음성 연결').click();await saved();
  await b('규칙 추가').click();await label('규칙 ID').fill('authored-audio');await label('WHEN 이벤트').selectOption('custom_event');await label('WHEN 사용자 이벤트 이름').fill('visitor.audio');await label('THEN 동작 1').selectOption('play_audio');await label('오디오 볼륨 1').fill('0.5');await b('규칙 적용').click();await saved();await page.getByRole('button',{name:'기록된 ETag로 서버 저장',exact:true}).click();await expect(page.getByRole('status',{name:'전시 편집 상태',exact:true})).toContainText('서버 revision');await saved();
  await check('protected save rejects unknown DSL versions and dangling references without replacing ETag',async()=>{
   const session=await (await context.request.get(`${origin}/api/v1/auth/session`)).json(),r=await record();
   for(const mutate of [p=>{p.version=2;},p=>{p.rules[0].actions[1].lightId=randomUUID();}]){const bad=structuredClone(r.draft);mutate(bad.candidate.extensions[NS]);const response=await context.request.put(`${origin}/api/v1/tenants/${authoring.tenantId}/studio/exhibitions/${r.remote.id}`,{headers:{origin,'x-csrf-token':session.csrfToken,'if-match':r.remote.etag},data:{requestId:randomUUID(),draft:bad}});assert.equal(response.status(),422);assert.equal((await response.json()).code,'DRAFT_INVALID');}
   const current=await context.request.get(`${origin}/api/v1/tenants/${authoring.tenantId}/studio/exhibitions/${r.remote.id}`);assert.equal(current.headers().etag,r.remote.etag);
  });
  await check('server READY and direct publication reject script audio without original text then allow restored draft',async()=>{
   const good=await stored(),missing=structuredClone(good);missing.extensions['org.exhibitos.viewer/experience'].voices=[];await page.getByLabel('전시 문서 JSON',{exact:true}).fill(JSON.stringify(missing));await saved();await button('기록된 ETag로 서버 저장').click();await expect(page.getByRole('status',{name:'전시 편집 상태',exact:true})).toContainText('서버 revision');await saved();await button('서버 revision READY 검사').click();await expect(page.getByTestId('ready-state')).toHaveText('BLOCKED');await expect(page.getByRole('region',{name:'READY 검사 결과',exact:true})).toContainText('SPATIAL_AUDIO_TRANSCRIPT');
   const session=await (await context.request.get(`${origin}/api/v1/auth/session`)).json(),r=await record(),response=await context.request.post(`${origin}/api/v1/tenants/${authoring.tenantId}/studio/exhibitions/${r.remote.id}/publications`,{headers:{origin,'x-csrf-token':session.csrfToken,'if-match':r.remote.etag},data:{requestId:randomUUID()}});assert.equal(response.status(),422);assert.equal((await response.json()).code,'PUBLICATION_NOT_READY');await page.getByLabel('전시 문서 JSON',{exact:true}).fill(JSON.stringify(good));await saved();await button('기록된 ETag로 서버 저장').click();await expect(page.getByRole('status',{name:'전시 편집 상태',exact:true})).toContainText('서버 revision');await saved();
  });
  await button('서버 revision READY 검사').click();await expect(page.getByTestId('ready-state')).toContainText('READY');await button('READY revision 공개').click();await expect(page.getByTestId('publication-status')).toContainText('공개');const href=await page.getByRole('link',{name:'익명 공개 preview 열기',exact:true}).getAttribute('href');assert(href);
  const anon=await browser.newContext(),viewer=await anon.newPage();viewer.setDefaultTimeout(30000);viewer.on('pageerror',e=>errors.push(e.message));let assetRequests=0;viewer.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/v1/publications/')&&new URL(r.url()).pathname.includes('/assets/'))assetRequests++;});await viewer.goto(`${origin}${href}`);
  const projection=await (await anon.request.get(`${origin}/api/v1/publications/${href.split('/').at(-1)}`)).json(),program=projection.exhibition.extensions[NS],rule=program.rules[0];assert.equal(rule.id,'authored-start');assert.equal(rule.actions[0].text,'Script source text '+candidate.rooms[0].id);assert.equal(rule.actions[1].lightId,projection.exhibition.lights[0].id);assert.equal(rule.actions[2].placementId,projection.exhibition.placements[0].id);assert.notEqual(rule.actions[1].lightId,candidate.lights[0].id);
  await check('anonymous default text view fetches no assets and does not run scripts',async()=>{assert.equal(assetRequests,0);assert.equal(await viewer.getByTestId('scripting-state').count(),0);});
  await viewer.getByRole('button',{name:'3D 관람 시작',exact:true}).click();await expect(viewer.getByTestId('scripting-state')).toBeVisible();
  const canvas=viewer.getByRole('region',{name:'전시 Viewer',exact:true}).locator('.geometry-preview canvas'),scene=()=>canvas.evaluate(c=>JSON.parse(c.dataset.scriptScene??'null')),state=()=>viewer.getByTestId('scripting-state').evaluate(e=>JSON.parse(e.dataset.scriptState));await expect.poll(scene).not.toBe(null);const original=await scene(),lightId=rule.actions[1].lightId,placementId=rule.actions[2].placementId;
  await check('actual Three scene follows delayed commands, immediate stop restores originals and cancels future effects',async()=>{
   assert.equal((await state()).enabled,false);await viewer.getByRole('button',{name:'스크립트 시작',exact:true}).click();await expect(viewer.getByTestId('script-visible-text')).toHaveText(rule.actions[0].text);await viewer.getByRole('button',{name:'스크립트 정지',exact:true}).click();await expect.poll(async()=>(await state()).enabled).toBe(false);await viewer.waitForTimeout(1800);assert.deepEqual(await scene(),original);
   await viewer.getByRole('button',{name:'스크립트 시작',exact:true}).click();await expect.poll(async()=>(await scene()).lights[lightId]).toBeCloseTo(original.lights[lightId]*.4,6);await expect.poll(async()=>(await scene()).visibility[placementId]).toBe(false);await viewer.keyboard.press('Escape');await expect.poll(scene).toEqual(original);assert.equal((await state()).pending,0);
  });
  await check('actual script PCM remains denied until both consents, plays verified audio and stops on mute',async()=>{
   const sound=()=>viewer.getByTestId('audio-state').evaluate(e=>JSON.parse(e.dataset.audioState));const action=viewer.getByRole('button',{name:'스크립트 동작 선택 authored-audio',exact:true});await viewer.getByRole('button',{name:'스크립트 시작',exact:true}).click();await expect.poll(async()=>(await state()).enabled).toBe(true);await action.click();assert.equal((await sound()).context,'not-created');assert.equal((await sound()).active,0);
   await viewer.getByLabel('스크립트 오디오 허용 (소리 켜기도 필요)',{exact:true}).check();await action.click();assert.equal((await sound()).context,'not-created');await viewer.getByRole('button',{name:'소리 켜기',exact:true}).click();await expect.poll(async()=>(await sound()).enabled).toBe(true);await action.click();await expect.poll(async()=>(await sound()).active).toBeGreaterThan(0);await viewer.getByLabel('소리 끄기',{exact:true}).check();await expect.poll(async()=>(await sound()).active).toBe(0);await viewer.getByRole('button',{name:'스크립트 정지',exact:true}).click();await expect.poll(scene).toEqual(original);const transcripts=viewer.getByRole('region',{name:'선택적 공간 스크립트',exact:true});await transcripts.getByText('소리 없이 읽는 원문 대본',{exact:true}).click();await expect(transcripts.getByText('Readable original script audio',{exact:true})).toBeVisible();
  });
  const screenshot=`${dir}/scripting-public.png`;await viewer.screenshot({path:screenshot,fullPage:true});await anon.close();assert.deepEqual(errors,[]);const report={checks,screenshots:[screenshot],scope:'Synthetic production Chromium, protected PostgreSQL save/publication, actual Three light/group mutation/reset. Verified synthetic PCM and both consent gates; physical VoiceOver/audibility not qualified here.'};await writeFile(`${dir}/scripting-run.json`,JSON.stringify(report,null,2));return report;
 }catch(error){await page.screenshot({path:`${dir}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${dir}/failure.json`,JSON.stringify({checks,error:String(error),errors,status:await page.getByRole('status').allTextContents().catch(()=>[])},null,2));console.error(`SCRIPTING FAILURE ${dir}`);throw error;}finally{await browser.close();}
}
