// SPDX-License-Identifier: AGPL-3.0-or-later
import { test } from "node:test";
import assert from "node:assert/strict";
import { denseCubeGlb, syntheticPng } from "./viewer-fixtures.mjs";
import { derivative } from "../apps/api/dist/derivative.js";
import { measureFullVariant, viewerVariants } from "../apps/api/dist/viewer-variants.js";
function changeGlb(bytes,edit){const size=bytes.readUInt32LE(12),doc=JSON.parse(bytes.toString("utf8",20,20+size));edit(doc);const json=Buffer.from(JSON.stringify(doc)),body=bytes.subarray(20+size),padded=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]),head=Buffer.from(bytes.subarray(0,20));head.writeUInt32LE(head.length+padded.length+body.length,8);head.writeUInt32LE(padded.length,12);return Buffer.concat([head,padded,body]);}
test("bounded isolated generation preserves physical extents and declared materials while reducing actual GLB/PNG bytes",async()=>{for(const [mime,source] of [["model/gltf-binary",denseCubeGlb()],["image/png",syntheticPng()]]){const full=await derivative(source,mime,{maxTextureSize:2048}),low=await viewerVariants(full,mime);assert.deepEqual(low.full,measureFullVariant(full,mime));assert.ok(low.bytes.length<full.length);if(mime==="model/gltf-binary"){const parse=b=>JSON.parse(b.toString("utf8",20,20+b.readUInt32LE(12))),a=parse(full),b=parse(low.bytes);assert.deepEqual(b.materials,a.materials);for(let i=0;i<a.meshes.length;i++){const aPos=a.accessors[a.meshes[i].primitives[0].attributes.POSITION],bPos=b.accessors[b.meshes[i].primitives[0].attributes.POSITION];for(let axis=0;axis<3;axis++){assert.ok(Math.abs(bPos.min[axis]-aPos.min[axis])<1e-6);assert.ok(Math.abs(bPos.max[axis]-aPos.max[axis])<1e-6);}}assert.ok(low.coarse.triangles<low.full.triangles);}else{assert.equal(low.coarse.textureSize,512);assert.equal(low.full.textureSize,2048);}}});
test("qualified complex full remains measured when bounded coarse index profile refuses it",async()=>{const full=await derivative(denseCubeGlb(96),"model/gltf-binary"),metric=measureFullVariant(full,"model/gltf-binary");assert.ok(metric.triangles>100000);await assert.rejects(viewerVariants(full,"model/gltf-binary"),/COARSE_UNAVAILABLE/);assert.deepEqual(measureFullVariant(full,"model/gltf-binary"),metric);});
test("invalid accessor bounds and explicit child timeout are rejected without coarse output",async()=>{const malformed=changeGlb(denseCubeGlb(),d=>{d.bufferViews[0].byteLength=4;});await assert.rejects(viewerVariants(malformed,"model/gltf-binary"),/COARSE_UNAVAILABLE/);await assert.rejects(viewerVariants(syntheticPng(),"image/png",{timeoutMs:1}),/COARSE_UNAVAILABLE/);});
